// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Checkly
{
    /// <summary>
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Checkly = Pulumi.Checkly;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var maintenance_1 = new Checkly.MaintenanceWindow("maintenance-1", new()
    ///     {
    ///         Name = "Maintenance Windows",
    ///         StartsAt = "2014-08-24T00:00:00.000Z",
    ///         EndsAt = "2014-08-25T00:00:00.000Z",
    ///         RepeatUnit = "MONTH",
    ///         RepeatEndsAt = "2014-08-24T00:00:00.000Z",
    ///         RepeatInterval = 1,
    ///         Tags = new[]
    ///         {
    ///             "production",
    ///         },
    ///         Timezone = "America/New_York",
    ///         Description = "Monthly database maintenance",
    ///         SilenceAlertsTags = new[]
    ///         {
    ///             "production",
    ///         },
    ///     });
    /// 
    ///     // Show a maintenance window on a status page
    ///     var api = new Checkly.StatusPageService("api", new()
    ///     {
    ///         Name = "API",
    ///     });
    /// 
    ///     var example = new Checkly.StatusPage("example", new()
    ///     {
    ///         Name = "Example Application",
    ///         Url = "my-example-status-page",
    ///         Cards = new[]
    ///         {
    ///             new Checkly.Inputs.StatusPageCardArgs
    ///             {
    ///                 Name = "Services",
    ///                 ServiceAttachments = new[]
    ///                 {
    ///                     new Checkly.Inputs.StatusPageCardServiceAttachmentArgs
    ///                     {
    ///                         ServiceId = api.Id,
    ///                     },
    ///                 },
    ///             },
    ///         },
    ///     });
    /// 
    ///     var maintenance_2 = new Checkly.MaintenanceWindow("maintenance-2", new()
    ///     {
    ///         Name = "Status page maintenance",
    ///         StartsAt = "2028-08-24T00:00:00.000Z",
    ///         EndsAt = "2028-08-24T02:00:00.000Z",
    ///         Tags = new[]
    ///         {
    ///             "api",
    ///         },
    ///         Description = "We're upgrading our API servers.",
    ///         StatusPageVisibility = new Checkly.Inputs.MaintenanceWindowStatusPageVisibilityArgs
    ///         {
    ///             Enabled = true,
    ///             Severity = "MINOR",
    ///             NotifyOnStart = true,
    ///             StatusPageIds = new[]
    ///             {
    ///                 example.Id,
    ///             },
    ///             ServiceIds = new[]
    ///             {
    ///                 api.Id,
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [ChecklyResourceType("checkly:index/maintenanceWindow:MaintenanceWindow")]
    public partial class MaintenanceWindow : global::Pulumi.CustomResource
    {
        /// <summary>
        /// A description of the maintenance window. When the window is visible on status pages, the description is shown there too.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The end date of the maintenance window.
        /// </summary>
        [Output("endsAt")]
        public Output<string> EndsAt { get; private set; } = null!;

        /// <summary>
        /// The maintenance window name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Pause every check in the account during the maintenance window, regardless of `tags`. Defaults to `false`.
        /// </summary>
        [Output("pauseAllChecks")]
        public Output<bool?> PauseAllChecks { get; private set; } = null!;

        /// <summary>
        /// The date on which the maintenance window should stop repeating, interpreted as a calendar date in `timezone`.
        /// </summary>
        [Output("repeatEndsAt")]
        public Output<string?> RepeatEndsAt { get; private set; } = null!;

        /// <summary>
        /// The repeat interval of the maintenance window from the first occurrence.
        /// </summary>
        [Output("repeatInterval")]
        public Output<int?> RepeatInterval { get; private set; } = null!;

        /// <summary>
        /// The repeat cadence for the maintenance window. Possible values `DAY`, `WEEK` and `MONTH`.
        /// </summary>
        [Output("repeatUnit")]
        public Output<string?> RepeatUnit { get; private set; } = null!;

        /// <summary>
        /// The tags of the checks and groups whose alerts are silenced during the maintenance window. Ignored when `silence_all_alerts` is `true`.
        /// </summary>
        [Output("silenceAlertsTags")]
        public Output<ImmutableArray<string>> SilenceAlertsTags { get; private set; } = null!;

        /// <summary>
        /// Silence alerts for every check in the account during the maintenance window, regardless of `silence_alerts_tags`. Defaults to `false`.
        /// </summary>
        [Output("silenceAllAlerts")]
        public Output<bool?> SilenceAllAlerts { get; private set; } = null!;

        /// <summary>
        /// The start date of the maintenance window.
        /// </summary>
        [Output("startsAt")]
        public Output<string> StartsAt { get; private set; } = null!;

        /// <summary>
        /// Whether and how the maintenance window appears on status pages. Omitting the block hides the window and unlinks it from all status pages and services. Only service-based status page links are supported; links to status page components can't be managed here. An account without the status page maintenance windows entitlement can only change `enabled` to `false`: keep the rest of the block as it is, because removing the block also changes the other settings, which is rejected.
        /// </summary>
        [Output("statusPageVisibility")]
        public Output<Outputs.MaintenanceWindowStatusPageVisibility?> StatusPageVisibility { get; private set; } = null!;

        /// <summary>
        /// The tags of the checks and groups that are paused during the maintenance window. Ignored when `pause_all_checks` is `true`.
        /// </summary>
        [Output("tags")]
        public Output<ImmutableArray<string>> Tags { get; private set; } = null!;

        /// <summary>
        /// The named IANA time zone used to schedule recurring occurrences, e.g. `America/New_York`. Occurrences keep the same local time across daylight-saving changes. `starts_at` and `ends_at` remain absolute instants; the time zone does not reinterpret them. Use the canonical IANA name (e.g. `America/New_York`, not `US/Eastern`): the API stores canonical names, so an alias shows as a change on every plan. UTC offsets such as `+05:00` or `Etc/GMT+5` are not accepted. Defaults to `UTC`. The time zone cannot be changed while a maintenance is active.
        /// </summary>
        [Output("timezone")]
        public Output<string?> Timezone { get; private set; } = null!;


        /// <summary>
        /// Create a MaintenanceWindow resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public MaintenanceWindow(string name, MaintenanceWindowArgs args, CustomResourceOptions? options = null)
            : base("checkly:index/maintenanceWindow:MaintenanceWindow", name, args ?? new MaintenanceWindowArgs(), MakeResourceOptions(options, ""))
        {
        }

        private MaintenanceWindow(string name, Input<string> id, MaintenanceWindowState? state = null, CustomResourceOptions? options = null)
            : base("checkly:index/maintenanceWindow:MaintenanceWindow", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/checkly",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing MaintenanceWindow resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static MaintenanceWindow Get(string name, Input<string> id, MaintenanceWindowState? state = null, CustomResourceOptions? options = null)
        {
            return new MaintenanceWindow(name, id, state, options);
        }
    }

    public sealed class MaintenanceWindowArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A description of the maintenance window. When the window is visible on status pages, the description is shown there too.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The end date of the maintenance window.
        /// </summary>
        [Input("endsAt", required: true)]
        public Input<string> EndsAt { get; set; } = null!;

        /// <summary>
        /// The maintenance window name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Pause every check in the account during the maintenance window, regardless of `tags`. Defaults to `false`.
        /// </summary>
        [Input("pauseAllChecks")]
        public Input<bool>? PauseAllChecks { get; set; }

        /// <summary>
        /// The date on which the maintenance window should stop repeating, interpreted as a calendar date in `timezone`.
        /// </summary>
        [Input("repeatEndsAt")]
        public Input<string>? RepeatEndsAt { get; set; }

        /// <summary>
        /// The repeat interval of the maintenance window from the first occurrence.
        /// </summary>
        [Input("repeatInterval")]
        public Input<int>? RepeatInterval { get; set; }

        /// <summary>
        /// The repeat cadence for the maintenance window. Possible values `DAY`, `WEEK` and `MONTH`.
        /// </summary>
        [Input("repeatUnit")]
        public Input<string>? RepeatUnit { get; set; }

        [Input("silenceAlertsTags")]
        private InputList<string>? _silenceAlertsTags;

        /// <summary>
        /// The tags of the checks and groups whose alerts are silenced during the maintenance window. Ignored when `silence_all_alerts` is `true`.
        /// </summary>
        public InputList<string> SilenceAlertsTags
        {
            get => _silenceAlertsTags ?? (_silenceAlertsTags = new InputList<string>());
            set => _silenceAlertsTags = value;
        }

        /// <summary>
        /// Silence alerts for every check in the account during the maintenance window, regardless of `silence_alerts_tags`. Defaults to `false`.
        /// </summary>
        [Input("silenceAllAlerts")]
        public Input<bool>? SilenceAllAlerts { get; set; }

        /// <summary>
        /// The start date of the maintenance window.
        /// </summary>
        [Input("startsAt", required: true)]
        public Input<string> StartsAt { get; set; } = null!;

        /// <summary>
        /// Whether and how the maintenance window appears on status pages. Omitting the block hides the window and unlinks it from all status pages and services. Only service-based status page links are supported; links to status page components can't be managed here. An account without the status page maintenance windows entitlement can only change `enabled` to `false`: keep the rest of the block as it is, because removing the block also changes the other settings, which is rejected.
        /// </summary>
        [Input("statusPageVisibility")]
        public Input<Inputs.MaintenanceWindowStatusPageVisibilityArgs>? StatusPageVisibility { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// The tags of the checks and groups that are paused during the maintenance window. Ignored when `pause_all_checks` is `true`.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// The named IANA time zone used to schedule recurring occurrences, e.g. `America/New_York`. Occurrences keep the same local time across daylight-saving changes. `starts_at` and `ends_at` remain absolute instants; the time zone does not reinterpret them. Use the canonical IANA name (e.g. `America/New_York`, not `US/Eastern`): the API stores canonical names, so an alias shows as a change on every plan. UTC offsets such as `+05:00` or `Etc/GMT+5` are not accepted. Defaults to `UTC`. The time zone cannot be changed while a maintenance is active.
        /// </summary>
        [Input("timezone")]
        public Input<string>? Timezone { get; set; }

        public MaintenanceWindowArgs()
        {
        }
        public static new MaintenanceWindowArgs Empty => new MaintenanceWindowArgs();
    }

    public sealed class MaintenanceWindowState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A description of the maintenance window. When the window is visible on status pages, the description is shown there too.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The end date of the maintenance window.
        /// </summary>
        [Input("endsAt")]
        public Input<string>? EndsAt { get; set; }

        /// <summary>
        /// The maintenance window name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Pause every check in the account during the maintenance window, regardless of `tags`. Defaults to `false`.
        /// </summary>
        [Input("pauseAllChecks")]
        public Input<bool>? PauseAllChecks { get; set; }

        /// <summary>
        /// The date on which the maintenance window should stop repeating, interpreted as a calendar date in `timezone`.
        /// </summary>
        [Input("repeatEndsAt")]
        public Input<string>? RepeatEndsAt { get; set; }

        /// <summary>
        /// The repeat interval of the maintenance window from the first occurrence.
        /// </summary>
        [Input("repeatInterval")]
        public Input<int>? RepeatInterval { get; set; }

        /// <summary>
        /// The repeat cadence for the maintenance window. Possible values `DAY`, `WEEK` and `MONTH`.
        /// </summary>
        [Input("repeatUnit")]
        public Input<string>? RepeatUnit { get; set; }

        [Input("silenceAlertsTags")]
        private InputList<string>? _silenceAlertsTags;

        /// <summary>
        /// The tags of the checks and groups whose alerts are silenced during the maintenance window. Ignored when `silence_all_alerts` is `true`.
        /// </summary>
        public InputList<string> SilenceAlertsTags
        {
            get => _silenceAlertsTags ?? (_silenceAlertsTags = new InputList<string>());
            set => _silenceAlertsTags = value;
        }

        /// <summary>
        /// Silence alerts for every check in the account during the maintenance window, regardless of `silence_alerts_tags`. Defaults to `false`.
        /// </summary>
        [Input("silenceAllAlerts")]
        public Input<bool>? SilenceAllAlerts { get; set; }

        /// <summary>
        /// The start date of the maintenance window.
        /// </summary>
        [Input("startsAt")]
        public Input<string>? StartsAt { get; set; }

        /// <summary>
        /// Whether and how the maintenance window appears on status pages. Omitting the block hides the window and unlinks it from all status pages and services. Only service-based status page links are supported; links to status page components can't be managed here. An account without the status page maintenance windows entitlement can only change `enabled` to `false`: keep the rest of the block as it is, because removing the block also changes the other settings, which is rejected.
        /// </summary>
        [Input("statusPageVisibility")]
        public Input<Inputs.MaintenanceWindowStatusPageVisibilityGetArgs>? StatusPageVisibility { get; set; }

        [Input("tags")]
        private InputList<string>? _tags;

        /// <summary>
        /// The tags of the checks and groups that are paused during the maintenance window. Ignored when `pause_all_checks` is `true`.
        /// </summary>
        public InputList<string> Tags
        {
            get => _tags ?? (_tags = new InputList<string>());
            set => _tags = value;
        }

        /// <summary>
        /// The named IANA time zone used to schedule recurring occurrences, e.g. `America/New_York`. Occurrences keep the same local time across daylight-saving changes. `starts_at` and `ends_at` remain absolute instants; the time zone does not reinterpret them. Use the canonical IANA name (e.g. `America/New_York`, not `US/Eastern`): the API stores canonical names, so an alias shows as a change on every plan. UTC offsets such as `+05:00` or `Etc/GMT+5` are not accepted. Defaults to `UTC`. The time zone cannot be changed while a maintenance is active.
        /// </summary>
        [Input("timezone")]
        public Input<string>? Timezone { get; set; }

        public MaintenanceWindowState()
        {
        }
        public static new MaintenanceWindowState Empty => new MaintenanceWindowState();
    }
}
