blank_issues_enabled: false
contact_links:
  - name: Docs
    url: https://www.checklyhq.com/product/pulumi-provider/
    about: If you need help, you can start checking out our documentation
  - name: API Reference
    url: https://developers.checklyhq.com
    about: The API is also a great way to help you debugging issues
  - name: Pulumi Provider Registry
    url: https://www.pulumi.com/registry/packages/checkly/
    about: The official Pulumi registry contains all the basic information about the provider resources
  - name: Questions
    url: https://github.com/checkly/pulumi-checkly/discussions
    about: Ask questions and discuss with other community members
