// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Checkly.Outputs
{

    [OutputType]
    public sealed class CheckGroupEnvironmentVariable
    {
        public readonly string Key;
        public readonly bool? Locked;
        public readonly bool? Secret;
        public readonly string Value;

        [OutputConstructor]
        private CheckGroupEnvironmentVariable(
            string key,

            bool? locked,

            bool? secret,

            string value)
        {
            Key = key;
            Locked = locked;
            Secret = secret;
            Value = value;
        }
    }
}
