// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package checkly

import (
	"context"
	"reflect"

	"errors"
	"github.com/checkly/pulumi-checkly/sdk/v2/go/checkly/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Creates an ICMP Monitor to check host availability using ping.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/checkly/pulumi-checkly/sdk/v2/go/checkly"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := checkly.NewIcmpMonitor(ctx, "example-icmp-monitor", &checkly.IcmpMonitorArgs{
//				Name:                   pulumi.String("Example ICMP monitor"),
//				Activated:              pulumi.Bool(true),
//				Frequency:              pulumi.Int(10),
//				UseGlobalAlertSettings: pulumi.Bool(true),
//				Locations: pulumi.StringArray{
//					pulumi.String("eu-west-1"),
//				},
//				Request: &checkly.IcmpMonitorRequestArgs{
//					Hostname:  pulumi.String("example.com"),
//					IpFamily:  pulumi.String("IPv4"),
//					PingCount: pulumi.Int(10),
//					Assertions: checkly.IcmpMonitorRequestAssertionArray{
//						&checkly.IcmpMonitorRequestAssertionArgs{
//							Source:     pulumi.String("LATENCY"),
//							Property:   pulumi.String("avg"),
//							Comparison: pulumi.String("LESS_THAN"),
//							Target:     pulumi.String("200"),
//						},
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
type IcmpMonitor struct {
	pulumi.CustomResourceState

	// Determines whether the monitor will run periodically or not after being deployed.
	Activated pulumi.BoolOutput `pulumi:"activated"`
	// An array of channel IDs and whether they're activated or not. If you don't set at least one alert subscription for your monitor, we won't be able to alert you.
	AlertChannelSubscriptions IcmpMonitorAlertChannelSubscriptionArrayOutput `pulumi:"alertChannelSubscriptions"`
	// Determines the alert escalation policy for the monitor.
	AlertSettings IcmpMonitorAlertSettingsOutput `pulumi:"alertSettings"`
	// The packet loss percentage where the monitor should be considered degraded. Possible values are between `0` and `100`. (Default `10`).
	DegradedPacketLossThreshold pulumi.IntPtrOutput `pulumi:"degradedPacketLossThreshold"`
	// Controls how often the monitor should run. Defined in minutes. The allowed values are `0` (high frequency - use `frequencyOffset` to define the actual frequency), `1` (1 minute), `2` (2 minutes), `5` (5 minutes), `10` (10 minutes), `15` (15 minutes), `30` (30 minutes), `60` (1 hour), `120` (2 hours), `180` (3 hours), `360` (6 hours), `720` (12 hours) and `1440` (24 hours).
	Frequency pulumi.IntOutput `pulumi:"frequency"`
	// When `frequency` is `0` (high frequency), `frequencyOffset` is required and it alone controls how often the monitor should run. Defined in seconds. The allowed values are `0` (disabled - use `frequency` to define the actual frequency), `10` (10 seconds), `20` (20 seconds) and `30` (30 seconds).
	FrequencyOffset pulumi.IntPtrOutput `pulumi:"frequencyOffset"`
	// The ID of the check group that this monitor is part of.
	GroupId pulumi.IntPtrOutput `pulumi:"groupId"`
	// The position of the monitor in the check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
	GroupOrder pulumi.IntPtrOutput `pulumi:"groupOrder"`
	// An array of one or more data center locations where to run this monitor.
	Locations pulumi.StringArrayOutput `pulumi:"locations"`
	// The packet loss percentage where the monitor should be considered failing. Possible values are between `0` and `100`. (Default `20`).
	MaxPacketLossThreshold pulumi.IntPtrOutput `pulumi:"maxPacketLossThreshold"`
	// Determines if any notifications will be sent out when the monitor fails and/or recovers. (Default `false`).
	Muted pulumi.BoolPtrOutput `pulumi:"muted"`
	// The name of the monitor.
	Name pulumi.StringOutput `pulumi:"name"`
	// The parameters of the ICMP request.
	Request IcmpMonitorRequestOutput `pulumi:"request"`
	// A strategy for retrying failed check/monitor runs.
	RetryStrategy IcmpMonitorRetryStrategyOutput `pulumi:"retryStrategy"`
	// Determines whether the monitor should run on all selected locations in parallel or round-robin. (Default `false`).
	RunParallel pulumi.BoolPtrOutput `pulumi:"runParallel"`
	// A list of tags for organizing and filtering checks and monitors.
	Tags pulumi.StringArrayOutput `pulumi:"tags"`
	// Create and resolve an incident based on the alert configuration. Useful for status page automation.
	TriggerIncident IcmpMonitorTriggerIncidentPtrOutput `pulumi:"triggerIncident"`
	// When true, the account level alert settings will be used, not the alert setting defined on this monitor. (Default `true`).
	UseGlobalAlertSettings pulumi.BoolPtrOutput `pulumi:"useGlobalAlertSettings"`
}

// NewIcmpMonitor registers a new resource with the given unique name, arguments, and options.
func NewIcmpMonitor(ctx *pulumi.Context,
	name string, args *IcmpMonitorArgs, opts ...pulumi.ResourceOption) (*IcmpMonitor, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Activated == nil {
		return nil, errors.New("invalid value for required argument 'Activated'")
	}
	if args.Frequency == nil {
		return nil, errors.New("invalid value for required argument 'Frequency'")
	}
	if args.Request == nil {
		return nil, errors.New("invalid value for required argument 'Request'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource IcmpMonitor
	err := ctx.RegisterResource("checkly:index/icmpMonitor:IcmpMonitor", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIcmpMonitor gets an existing IcmpMonitor resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIcmpMonitor(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IcmpMonitorState, opts ...pulumi.ResourceOption) (*IcmpMonitor, error) {
	var resource IcmpMonitor
	err := ctx.ReadResource("checkly:index/icmpMonitor:IcmpMonitor", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering IcmpMonitor resources.
type icmpMonitorState struct {
	// Determines whether the monitor will run periodically or not after being deployed.
	Activated *bool `pulumi:"activated"`
	// An array of channel IDs and whether they're activated or not. If you don't set at least one alert subscription for your monitor, we won't be able to alert you.
	AlertChannelSubscriptions []IcmpMonitorAlertChannelSubscription `pulumi:"alertChannelSubscriptions"`
	// Determines the alert escalation policy for the monitor.
	AlertSettings *IcmpMonitorAlertSettings `pulumi:"alertSettings"`
	// The packet loss percentage where the monitor should be considered degraded. Possible values are between `0` and `100`. (Default `10`).
	DegradedPacketLossThreshold *int `pulumi:"degradedPacketLossThreshold"`
	// Controls how often the monitor should run. Defined in minutes. The allowed values are `0` (high frequency - use `frequencyOffset` to define the actual frequency), `1` (1 minute), `2` (2 minutes), `5` (5 minutes), `10` (10 minutes), `15` (15 minutes), `30` (30 minutes), `60` (1 hour), `120` (2 hours), `180` (3 hours), `360` (6 hours), `720` (12 hours) and `1440` (24 hours).
	Frequency *int `pulumi:"frequency"`
	// When `frequency` is `0` (high frequency), `frequencyOffset` is required and it alone controls how often the monitor should run. Defined in seconds. The allowed values are `0` (disabled - use `frequency` to define the actual frequency), `10` (10 seconds), `20` (20 seconds) and `30` (30 seconds).
	FrequencyOffset *int `pulumi:"frequencyOffset"`
	// The ID of the check group that this monitor is part of.
	GroupId *int `pulumi:"groupId"`
	// The position of the monitor in the check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
	GroupOrder *int `pulumi:"groupOrder"`
	// An array of one or more data center locations where to run this monitor.
	Locations []string `pulumi:"locations"`
	// The packet loss percentage where the monitor should be considered failing. Possible values are between `0` and `100`. (Default `20`).
	MaxPacketLossThreshold *int `pulumi:"maxPacketLossThreshold"`
	// Determines if any notifications will be sent out when the monitor fails and/or recovers. (Default `false`).
	Muted *bool `pulumi:"muted"`
	// The name of the monitor.
	Name *string `pulumi:"name"`
	// The parameters of the ICMP request.
	Request *IcmpMonitorRequest `pulumi:"request"`
	// A strategy for retrying failed check/monitor runs.
	RetryStrategy *IcmpMonitorRetryStrategy `pulumi:"retryStrategy"`
	// Determines whether the monitor should run on all selected locations in parallel or round-robin. (Default `false`).
	RunParallel *bool `pulumi:"runParallel"`
	// A list of tags for organizing and filtering checks and monitors.
	Tags []string `pulumi:"tags"`
	// Create and resolve an incident based on the alert configuration. Useful for status page automation.
	TriggerIncident *IcmpMonitorTriggerIncident `pulumi:"triggerIncident"`
	// When true, the account level alert settings will be used, not the alert setting defined on this monitor. (Default `true`).
	UseGlobalAlertSettings *bool `pulumi:"useGlobalAlertSettings"`
}

type IcmpMonitorState struct {
	// Determines whether the monitor will run periodically or not after being deployed.
	Activated pulumi.BoolPtrInput
	// An array of channel IDs and whether they're activated or not. If you don't set at least one alert subscription for your monitor, we won't be able to alert you.
	AlertChannelSubscriptions IcmpMonitorAlertChannelSubscriptionArrayInput
	// Determines the alert escalation policy for the monitor.
	AlertSettings IcmpMonitorAlertSettingsPtrInput
	// The packet loss percentage where the monitor should be considered degraded. Possible values are between `0` and `100`. (Default `10`).
	DegradedPacketLossThreshold pulumi.IntPtrInput
	// Controls how often the monitor should run. Defined in minutes. The allowed values are `0` (high frequency - use `frequencyOffset` to define the actual frequency), `1` (1 minute), `2` (2 minutes), `5` (5 minutes), `10` (10 minutes), `15` (15 minutes), `30` (30 minutes), `60` (1 hour), `120` (2 hours), `180` (3 hours), `360` (6 hours), `720` (12 hours) and `1440` (24 hours).
	Frequency pulumi.IntPtrInput
	// When `frequency` is `0` (high frequency), `frequencyOffset` is required and it alone controls how often the monitor should run. Defined in seconds. The allowed values are `0` (disabled - use `frequency` to define the actual frequency), `10` (10 seconds), `20` (20 seconds) and `30` (30 seconds).
	FrequencyOffset pulumi.IntPtrInput
	// The ID of the check group that this monitor is part of.
	GroupId pulumi.IntPtrInput
	// The position of the monitor in the check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
	GroupOrder pulumi.IntPtrInput
	// An array of one or more data center locations where to run this monitor.
	Locations pulumi.StringArrayInput
	// The packet loss percentage where the monitor should be considered failing. Possible values are between `0` and `100`. (Default `20`).
	MaxPacketLossThreshold pulumi.IntPtrInput
	// Determines if any notifications will be sent out when the monitor fails and/or recovers. (Default `false`).
	Muted pulumi.BoolPtrInput
	// The name of the monitor.
	Name pulumi.StringPtrInput
	// The parameters of the ICMP request.
	Request IcmpMonitorRequestPtrInput
	// A strategy for retrying failed check/monitor runs.
	RetryStrategy IcmpMonitorRetryStrategyPtrInput
	// Determines whether the monitor should run on all selected locations in parallel or round-robin. (Default `false`).
	RunParallel pulumi.BoolPtrInput
	// A list of tags for organizing and filtering checks and monitors.
	Tags pulumi.StringArrayInput
	// Create and resolve an incident based on the alert configuration. Useful for status page automation.
	TriggerIncident IcmpMonitorTriggerIncidentPtrInput
	// When true, the account level alert settings will be used, not the alert setting defined on this monitor. (Default `true`).
	UseGlobalAlertSettings pulumi.BoolPtrInput
}

func (IcmpMonitorState) ElementType() reflect.Type {
	return reflect.TypeOf((*icmpMonitorState)(nil)).Elem()
}

type icmpMonitorArgs struct {
	// Determines whether the monitor will run periodically or not after being deployed.
	Activated bool `pulumi:"activated"`
	// An array of channel IDs and whether they're activated or not. If you don't set at least one alert subscription for your monitor, we won't be able to alert you.
	AlertChannelSubscriptions []IcmpMonitorAlertChannelSubscription `pulumi:"alertChannelSubscriptions"`
	// Determines the alert escalation policy for the monitor.
	AlertSettings *IcmpMonitorAlertSettings `pulumi:"alertSettings"`
	// The packet loss percentage where the monitor should be considered degraded. Possible values are between `0` and `100`. (Default `10`).
	DegradedPacketLossThreshold *int `pulumi:"degradedPacketLossThreshold"`
	// Controls how often the monitor should run. Defined in minutes. The allowed values are `0` (high frequency - use `frequencyOffset` to define the actual frequency), `1` (1 minute), `2` (2 minutes), `5` (5 minutes), `10` (10 minutes), `15` (15 minutes), `30` (30 minutes), `60` (1 hour), `120` (2 hours), `180` (3 hours), `360` (6 hours), `720` (12 hours) and `1440` (24 hours).
	Frequency int `pulumi:"frequency"`
	// When `frequency` is `0` (high frequency), `frequencyOffset` is required and it alone controls how often the monitor should run. Defined in seconds. The allowed values are `0` (disabled - use `frequency` to define the actual frequency), `10` (10 seconds), `20` (20 seconds) and `30` (30 seconds).
	FrequencyOffset *int `pulumi:"frequencyOffset"`
	// The ID of the check group that this monitor is part of.
	GroupId *int `pulumi:"groupId"`
	// The position of the monitor in the check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
	GroupOrder *int `pulumi:"groupOrder"`
	// An array of one or more data center locations where to run this monitor.
	Locations []string `pulumi:"locations"`
	// The packet loss percentage where the monitor should be considered failing. Possible values are between `0` and `100`. (Default `20`).
	MaxPacketLossThreshold *int `pulumi:"maxPacketLossThreshold"`
	// Determines if any notifications will be sent out when the monitor fails and/or recovers. (Default `false`).
	Muted *bool `pulumi:"muted"`
	// The name of the monitor.
	Name *string `pulumi:"name"`
	// The parameters of the ICMP request.
	Request IcmpMonitorRequest `pulumi:"request"`
	// A strategy for retrying failed check/monitor runs.
	RetryStrategy *IcmpMonitorRetryStrategy `pulumi:"retryStrategy"`
	// Determines whether the monitor should run on all selected locations in parallel or round-robin. (Default `false`).
	RunParallel *bool `pulumi:"runParallel"`
	// A list of tags for organizing and filtering checks and monitors.
	Tags []string `pulumi:"tags"`
	// Create and resolve an incident based on the alert configuration. Useful for status page automation.
	TriggerIncident *IcmpMonitorTriggerIncident `pulumi:"triggerIncident"`
	// When true, the account level alert settings will be used, not the alert setting defined on this monitor. (Default `true`).
	UseGlobalAlertSettings *bool `pulumi:"useGlobalAlertSettings"`
}

// The set of arguments for constructing a IcmpMonitor resource.
type IcmpMonitorArgs struct {
	// Determines whether the monitor will run periodically or not after being deployed.
	Activated pulumi.BoolInput
	// An array of channel IDs and whether they're activated or not. If you don't set at least one alert subscription for your monitor, we won't be able to alert you.
	AlertChannelSubscriptions IcmpMonitorAlertChannelSubscriptionArrayInput
	// Determines the alert escalation policy for the monitor.
	AlertSettings IcmpMonitorAlertSettingsPtrInput
	// The packet loss percentage where the monitor should be considered degraded. Possible values are between `0` and `100`. (Default `10`).
	DegradedPacketLossThreshold pulumi.IntPtrInput
	// Controls how often the monitor should run. Defined in minutes. The allowed values are `0` (high frequency - use `frequencyOffset` to define the actual frequency), `1` (1 minute), `2` (2 minutes), `5` (5 minutes), `10` (10 minutes), `15` (15 minutes), `30` (30 minutes), `60` (1 hour), `120` (2 hours), `180` (3 hours), `360` (6 hours), `720` (12 hours) and `1440` (24 hours).
	Frequency pulumi.IntInput
	// When `frequency` is `0` (high frequency), `frequencyOffset` is required and it alone controls how often the monitor should run. Defined in seconds. The allowed values are `0` (disabled - use `frequency` to define the actual frequency), `10` (10 seconds), `20` (20 seconds) and `30` (30 seconds).
	FrequencyOffset pulumi.IntPtrInput
	// The ID of the check group that this monitor is part of.
	GroupId pulumi.IntPtrInput
	// The position of the monitor in the check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
	GroupOrder pulumi.IntPtrInput
	// An array of one or more data center locations where to run this monitor.
	Locations pulumi.StringArrayInput
	// The packet loss percentage where the monitor should be considered failing. Possible values are between `0` and `100`. (Default `20`).
	MaxPacketLossThreshold pulumi.IntPtrInput
	// Determines if any notifications will be sent out when the monitor fails and/or recovers. (Default `false`).
	Muted pulumi.BoolPtrInput
	// The name of the monitor.
	Name pulumi.StringPtrInput
	// The parameters of the ICMP request.
	Request IcmpMonitorRequestInput
	// A strategy for retrying failed check/monitor runs.
	RetryStrategy IcmpMonitorRetryStrategyPtrInput
	// Determines whether the monitor should run on all selected locations in parallel or round-robin. (Default `false`).
	RunParallel pulumi.BoolPtrInput
	// A list of tags for organizing and filtering checks and monitors.
	Tags pulumi.StringArrayInput
	// Create and resolve an incident based on the alert configuration. Useful for status page automation.
	TriggerIncident IcmpMonitorTriggerIncidentPtrInput
	// When true, the account level alert settings will be used, not the alert setting defined on this monitor. (Default `true`).
	UseGlobalAlertSettings pulumi.BoolPtrInput
}

func (IcmpMonitorArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*icmpMonitorArgs)(nil)).Elem()
}

type IcmpMonitorInput interface {
	pulumi.Input

	ToIcmpMonitorOutput() IcmpMonitorOutput
	ToIcmpMonitorOutputWithContext(ctx context.Context) IcmpMonitorOutput
}

func (*IcmpMonitor) ElementType() reflect.Type {
	return reflect.TypeOf((**IcmpMonitor)(nil)).Elem()
}

func (i *IcmpMonitor) ToIcmpMonitorOutput() IcmpMonitorOutput {
	return i.ToIcmpMonitorOutputWithContext(context.Background())
}

func (i *IcmpMonitor) ToIcmpMonitorOutputWithContext(ctx context.Context) IcmpMonitorOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IcmpMonitorOutput)
}

// IcmpMonitorArrayInput is an input type that accepts IcmpMonitorArray and IcmpMonitorArrayOutput values.
// You can construct a concrete instance of `IcmpMonitorArrayInput` via:
//
//	IcmpMonitorArray{ IcmpMonitorArgs{...} }
type IcmpMonitorArrayInput interface {
	pulumi.Input

	ToIcmpMonitorArrayOutput() IcmpMonitorArrayOutput
	ToIcmpMonitorArrayOutputWithContext(context.Context) IcmpMonitorArrayOutput
}

type IcmpMonitorArray []IcmpMonitorInput

func (IcmpMonitorArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*IcmpMonitor)(nil)).Elem()
}

func (i IcmpMonitorArray) ToIcmpMonitorArrayOutput() IcmpMonitorArrayOutput {
	return i.ToIcmpMonitorArrayOutputWithContext(context.Background())
}

func (i IcmpMonitorArray) ToIcmpMonitorArrayOutputWithContext(ctx context.Context) IcmpMonitorArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IcmpMonitorArrayOutput)
}

// IcmpMonitorMapInput is an input type that accepts IcmpMonitorMap and IcmpMonitorMapOutput values.
// You can construct a concrete instance of `IcmpMonitorMapInput` via:
//
//	IcmpMonitorMap{ "key": IcmpMonitorArgs{...} }
type IcmpMonitorMapInput interface {
	pulumi.Input

	ToIcmpMonitorMapOutput() IcmpMonitorMapOutput
	ToIcmpMonitorMapOutputWithContext(context.Context) IcmpMonitorMapOutput
}

type IcmpMonitorMap map[string]IcmpMonitorInput

func (IcmpMonitorMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*IcmpMonitor)(nil)).Elem()
}

func (i IcmpMonitorMap) ToIcmpMonitorMapOutput() IcmpMonitorMapOutput {
	return i.ToIcmpMonitorMapOutputWithContext(context.Background())
}

func (i IcmpMonitorMap) ToIcmpMonitorMapOutputWithContext(ctx context.Context) IcmpMonitorMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IcmpMonitorMapOutput)
}

type IcmpMonitorOutput struct{ *pulumi.OutputState }

func (IcmpMonitorOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**IcmpMonitor)(nil)).Elem()
}

func (o IcmpMonitorOutput) ToIcmpMonitorOutput() IcmpMonitorOutput {
	return o
}

func (o IcmpMonitorOutput) ToIcmpMonitorOutputWithContext(ctx context.Context) IcmpMonitorOutput {
	return o
}

// Determines whether the monitor will run periodically or not after being deployed.
func (o IcmpMonitorOutput) Activated() pulumi.BoolOutput {
	return o.ApplyT(func(v *IcmpMonitor) pulumi.BoolOutput { return v.Activated }).(pulumi.BoolOutput)
}

// An array of channel IDs and whether they're activated or not. If you don't set at least one alert subscription for your monitor, we won't be able to alert you.
func (o IcmpMonitorOutput) AlertChannelSubscriptions() IcmpMonitorAlertChannelSubscriptionArrayOutput {
	return o.ApplyT(func(v *IcmpMonitor) IcmpMonitorAlertChannelSubscriptionArrayOutput {
		return v.AlertChannelSubscriptions
	}).(IcmpMonitorAlertChannelSubscriptionArrayOutput)
}

// Determines the alert escalation policy for the monitor.
func (o IcmpMonitorOutput) AlertSettings() IcmpMonitorAlertSettingsOutput {
	return o.ApplyT(func(v *IcmpMonitor) IcmpMonitorAlertSettingsOutput { return v.AlertSettings }).(IcmpMonitorAlertSettingsOutput)
}

// The packet loss percentage where the monitor should be considered degraded. Possible values are between `0` and `100`. (Default `10`).
func (o IcmpMonitorOutput) DegradedPacketLossThreshold() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *IcmpMonitor) pulumi.IntPtrOutput { return v.DegradedPacketLossThreshold }).(pulumi.IntPtrOutput)
}

// Controls how often the monitor should run. Defined in minutes. The allowed values are `0` (high frequency - use `frequencyOffset` to define the actual frequency), `1` (1 minute), `2` (2 minutes), `5` (5 minutes), `10` (10 minutes), `15` (15 minutes), `30` (30 minutes), `60` (1 hour), `120` (2 hours), `180` (3 hours), `360` (6 hours), `720` (12 hours) and `1440` (24 hours).
func (o IcmpMonitorOutput) Frequency() pulumi.IntOutput {
	return o.ApplyT(func(v *IcmpMonitor) pulumi.IntOutput { return v.Frequency }).(pulumi.IntOutput)
}

// When `frequency` is `0` (high frequency), `frequencyOffset` is required and it alone controls how often the monitor should run. Defined in seconds. The allowed values are `0` (disabled - use `frequency` to define the actual frequency), `10` (10 seconds), `20` (20 seconds) and `30` (30 seconds).
func (o IcmpMonitorOutput) FrequencyOffset() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *IcmpMonitor) pulumi.IntPtrOutput { return v.FrequencyOffset }).(pulumi.IntPtrOutput)
}

// The ID of the check group that this monitor is part of.
func (o IcmpMonitorOutput) GroupId() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *IcmpMonitor) pulumi.IntPtrOutput { return v.GroupId }).(pulumi.IntPtrOutput)
}

// The position of the monitor in the check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
func (o IcmpMonitorOutput) GroupOrder() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *IcmpMonitor) pulumi.IntPtrOutput { return v.GroupOrder }).(pulumi.IntPtrOutput)
}

// An array of one or more data center locations where to run this monitor.
func (o IcmpMonitorOutput) Locations() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *IcmpMonitor) pulumi.StringArrayOutput { return v.Locations }).(pulumi.StringArrayOutput)
}

// The packet loss percentage where the monitor should be considered failing. Possible values are between `0` and `100`. (Default `20`).
func (o IcmpMonitorOutput) MaxPacketLossThreshold() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *IcmpMonitor) pulumi.IntPtrOutput { return v.MaxPacketLossThreshold }).(pulumi.IntPtrOutput)
}

// Determines if any notifications will be sent out when the monitor fails and/or recovers. (Default `false`).
func (o IcmpMonitorOutput) Muted() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *IcmpMonitor) pulumi.BoolPtrOutput { return v.Muted }).(pulumi.BoolPtrOutput)
}

// The name of the monitor.
func (o IcmpMonitorOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *IcmpMonitor) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The parameters of the ICMP request.
func (o IcmpMonitorOutput) Request() IcmpMonitorRequestOutput {
	return o.ApplyT(func(v *IcmpMonitor) IcmpMonitorRequestOutput { return v.Request }).(IcmpMonitorRequestOutput)
}

// A strategy for retrying failed check/monitor runs.
func (o IcmpMonitorOutput) RetryStrategy() IcmpMonitorRetryStrategyOutput {
	return o.ApplyT(func(v *IcmpMonitor) IcmpMonitorRetryStrategyOutput { return v.RetryStrategy }).(IcmpMonitorRetryStrategyOutput)
}

// Determines whether the monitor should run on all selected locations in parallel or round-robin. (Default `false`).
func (o IcmpMonitorOutput) RunParallel() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *IcmpMonitor) pulumi.BoolPtrOutput { return v.RunParallel }).(pulumi.BoolPtrOutput)
}

// A list of tags for organizing and filtering checks and monitors.
func (o IcmpMonitorOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *IcmpMonitor) pulumi.StringArrayOutput { return v.Tags }).(pulumi.StringArrayOutput)
}

// Create and resolve an incident based on the alert configuration. Useful for status page automation.
func (o IcmpMonitorOutput) TriggerIncident() IcmpMonitorTriggerIncidentPtrOutput {
	return o.ApplyT(func(v *IcmpMonitor) IcmpMonitorTriggerIncidentPtrOutput { return v.TriggerIncident }).(IcmpMonitorTriggerIncidentPtrOutput)
}

// When true, the account level alert settings will be used, not the alert setting defined on this monitor. (Default `true`).
func (o IcmpMonitorOutput) UseGlobalAlertSettings() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *IcmpMonitor) pulumi.BoolPtrOutput { return v.UseGlobalAlertSettings }).(pulumi.BoolPtrOutput)
}

type IcmpMonitorArrayOutput struct{ *pulumi.OutputState }

func (IcmpMonitorArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*IcmpMonitor)(nil)).Elem()
}

func (o IcmpMonitorArrayOutput) ToIcmpMonitorArrayOutput() IcmpMonitorArrayOutput {
	return o
}

func (o IcmpMonitorArrayOutput) ToIcmpMonitorArrayOutputWithContext(ctx context.Context) IcmpMonitorArrayOutput {
	return o
}

func (o IcmpMonitorArrayOutput) Index(i pulumi.IntInput) IcmpMonitorOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *IcmpMonitor {
		return vs[0].([]*IcmpMonitor)[vs[1].(int)]
	}).(IcmpMonitorOutput)
}

type IcmpMonitorMapOutput struct{ *pulumi.OutputState }

func (IcmpMonitorMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*IcmpMonitor)(nil)).Elem()
}

func (o IcmpMonitorMapOutput) ToIcmpMonitorMapOutput() IcmpMonitorMapOutput {
	return o
}

func (o IcmpMonitorMapOutput) ToIcmpMonitorMapOutputWithContext(ctx context.Context) IcmpMonitorMapOutput {
	return o
}

func (o IcmpMonitorMapOutput) MapIndex(k pulumi.StringInput) IcmpMonitorOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *IcmpMonitor {
		return vs[0].(map[string]*IcmpMonitor)[vs[1].(string)]
	}).(IcmpMonitorOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*IcmpMonitorInput)(nil)).Elem(), &IcmpMonitor{})
	pulumi.RegisterInputType(reflect.TypeOf((*IcmpMonitorArrayInput)(nil)).Elem(), IcmpMonitorArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*IcmpMonitorMapInput)(nil)).Elem(), IcmpMonitorMap{})
	pulumi.RegisterOutputType(IcmpMonitorOutput{})
	pulumi.RegisterOutputType(IcmpMonitorArrayOutput{})
	pulumi.RegisterOutputType(IcmpMonitorMapOutput{})
}
