# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = ['PublicDashboardArgs', 'PublicDashboard']

@pulumi.input_type
class PublicDashboardArgs:
    def __init__(__self__, *,
                 custom_domain: pulumi.Input[str],
                 custom_url: pulumi.Input[str],
                 hide_tags: pulumi.Input[bool],
                 paginate: pulumi.Input[bool],
                 pagination_rate: pulumi.Input[int],
                 refresh_rate: pulumi.Input[int],
                 header: Optional[pulumi.Input[str]] = None,
                 logo: Optional[pulumi.Input[str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 width: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a PublicDashboard resource.
        """
        pulumi.set(__self__, "custom_domain", custom_domain)
        pulumi.set(__self__, "custom_url", custom_url)
        pulumi.set(__self__, "hide_tags", hide_tags)
        pulumi.set(__self__, "paginate", paginate)
        pulumi.set(__self__, "pagination_rate", pagination_rate)
        pulumi.set(__self__, "refresh_rate", refresh_rate)
        if header is None:
            header = ''
        if header is not None:
            pulumi.set(__self__, "header", header)
        if logo is None:
            logo = ''
        if logo is not None:
            pulumi.set(__self__, "logo", logo)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if width is not None:
            pulumi.set(__self__, "width", width)

    @property
    @pulumi.getter(name="customDomain")
    def custom_domain(self) -> pulumi.Input[str]:
        return pulumi.get(self, "custom_domain")

    @custom_domain.setter
    def custom_domain(self, value: pulumi.Input[str]):
        pulumi.set(self, "custom_domain", value)

    @property
    @pulumi.getter(name="customUrl")
    def custom_url(self) -> pulumi.Input[str]:
        return pulumi.get(self, "custom_url")

    @custom_url.setter
    def custom_url(self, value: pulumi.Input[str]):
        pulumi.set(self, "custom_url", value)

    @property
    @pulumi.getter(name="hideTags")
    def hide_tags(self) -> pulumi.Input[bool]:
        return pulumi.get(self, "hide_tags")

    @hide_tags.setter
    def hide_tags(self, value: pulumi.Input[bool]):
        pulumi.set(self, "hide_tags", value)

    @property
    @pulumi.getter
    def paginate(self) -> pulumi.Input[bool]:
        return pulumi.get(self, "paginate")

    @paginate.setter
    def paginate(self, value: pulumi.Input[bool]):
        pulumi.set(self, "paginate", value)

    @property
    @pulumi.getter(name="paginationRate")
    def pagination_rate(self) -> pulumi.Input[int]:
        return pulumi.get(self, "pagination_rate")

    @pagination_rate.setter
    def pagination_rate(self, value: pulumi.Input[int]):
        pulumi.set(self, "pagination_rate", value)

    @property
    @pulumi.getter(name="refreshRate")
    def refresh_rate(self) -> pulumi.Input[int]:
        return pulumi.get(self, "refresh_rate")

    @refresh_rate.setter
    def refresh_rate(self, value: pulumi.Input[int]):
        pulumi.set(self, "refresh_rate", value)

    @property
    @pulumi.getter
    def header(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "header")

    @header.setter
    def header(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "header", value)

    @property
    @pulumi.getter
    def logo(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "logo")

    @logo.setter
    def logo(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "logo", value)

    @property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "tags", value)

    @property
    @pulumi.getter
    def width(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "width")

    @width.setter
    def width(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "width", value)


@pulumi.input_type
class _PublicDashboardState:
    def __init__(__self__, *,
                 custom_domain: Optional[pulumi.Input[str]] = None,
                 custom_url: Optional[pulumi.Input[str]] = None,
                 header: Optional[pulumi.Input[str]] = None,
                 hide_tags: Optional[pulumi.Input[bool]] = None,
                 logo: Optional[pulumi.Input[str]] = None,
                 paginate: Optional[pulumi.Input[bool]] = None,
                 pagination_rate: Optional[pulumi.Input[int]] = None,
                 refresh_rate: Optional[pulumi.Input[int]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 width: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering PublicDashboard resources.
        """
        if custom_domain is not None:
            pulumi.set(__self__, "custom_domain", custom_domain)
        if custom_url is not None:
            pulumi.set(__self__, "custom_url", custom_url)
        if header is None:
            header = ''
        if header is not None:
            pulumi.set(__self__, "header", header)
        if hide_tags is not None:
            pulumi.set(__self__, "hide_tags", hide_tags)
        if logo is None:
            logo = ''
        if logo is not None:
            pulumi.set(__self__, "logo", logo)
        if paginate is not None:
            pulumi.set(__self__, "paginate", paginate)
        if pagination_rate is not None:
            pulumi.set(__self__, "pagination_rate", pagination_rate)
        if refresh_rate is not None:
            pulumi.set(__self__, "refresh_rate", refresh_rate)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if width is not None:
            pulumi.set(__self__, "width", width)

    @property
    @pulumi.getter(name="customDomain")
    def custom_domain(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "custom_domain")

    @custom_domain.setter
    def custom_domain(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "custom_domain", value)

    @property
    @pulumi.getter(name="customUrl")
    def custom_url(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "custom_url")

    @custom_url.setter
    def custom_url(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "custom_url", value)

    @property
    @pulumi.getter
    def header(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "header")

    @header.setter
    def header(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "header", value)

    @property
    @pulumi.getter(name="hideTags")
    def hide_tags(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "hide_tags")

    @hide_tags.setter
    def hide_tags(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "hide_tags", value)

    @property
    @pulumi.getter
    def logo(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "logo")

    @logo.setter
    def logo(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "logo", value)

    @property
    @pulumi.getter
    def paginate(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "paginate")

    @paginate.setter
    def paginate(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "paginate", value)

    @property
    @pulumi.getter(name="paginationRate")
    def pagination_rate(self) -> Optional[pulumi.Input[int]]:
        return pulumi.get(self, "pagination_rate")

    @pagination_rate.setter
    def pagination_rate(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "pagination_rate", value)

    @property
    @pulumi.getter(name="refreshRate")
    def refresh_rate(self) -> Optional[pulumi.Input[int]]:
        return pulumi.get(self, "refresh_rate")

    @refresh_rate.setter
    def refresh_rate(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "refresh_rate", value)

    @property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "tags", value)

    @property
    @pulumi.getter
    def width(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "width")

    @width.setter
    def width(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "width", value)


class PublicDashboard(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 custom_domain: Optional[pulumi.Input[str]] = None,
                 custom_url: Optional[pulumi.Input[str]] = None,
                 header: Optional[pulumi.Input[str]] = None,
                 hide_tags: Optional[pulumi.Input[bool]] = None,
                 logo: Optional[pulumi.Input[str]] = None,
                 paginate: Optional[pulumi.Input[bool]] = None,
                 pagination_rate: Optional[pulumi.Input[int]] = None,
                 refresh_rate: Optional[pulumi.Input[int]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 width: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a PublicDashboard resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: PublicDashboardArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a PublicDashboard resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param PublicDashboardArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PublicDashboardArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 custom_domain: Optional[pulumi.Input[str]] = None,
                 custom_url: Optional[pulumi.Input[str]] = None,
                 header: Optional[pulumi.Input[str]] = None,
                 hide_tags: Optional[pulumi.Input[bool]] = None,
                 logo: Optional[pulumi.Input[str]] = None,
                 paginate: Optional[pulumi.Input[bool]] = None,
                 pagination_rate: Optional[pulumi.Input[int]] = None,
                 refresh_rate: Optional[pulumi.Input[int]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 width: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = _utilities.get_version()
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PublicDashboardArgs.__new__(PublicDashboardArgs)

            if custom_domain is None and not opts.urn:
                raise TypeError("Missing required property 'custom_domain'")
            __props__.__dict__["custom_domain"] = custom_domain
            if custom_url is None and not opts.urn:
                raise TypeError("Missing required property 'custom_url'")
            __props__.__dict__["custom_url"] = custom_url
            if header is None:
                header = ''
            __props__.__dict__["header"] = header
            if hide_tags is None and not opts.urn:
                raise TypeError("Missing required property 'hide_tags'")
            __props__.__dict__["hide_tags"] = hide_tags
            if logo is None:
                logo = ''
            __props__.__dict__["logo"] = logo
            if paginate is None and not opts.urn:
                raise TypeError("Missing required property 'paginate'")
            __props__.__dict__["paginate"] = paginate
            if pagination_rate is None and not opts.urn:
                raise TypeError("Missing required property 'pagination_rate'")
            __props__.__dict__["pagination_rate"] = pagination_rate
            if refresh_rate is None and not opts.urn:
                raise TypeError("Missing required property 'refresh_rate'")
            __props__.__dict__["refresh_rate"] = refresh_rate
            __props__.__dict__["tags"] = tags
            __props__.__dict__["width"] = width
        super(PublicDashboard, __self__).__init__(
            'checkly:index/publicDashboard:PublicDashboard',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            custom_domain: Optional[pulumi.Input[str]] = None,
            custom_url: Optional[pulumi.Input[str]] = None,
            header: Optional[pulumi.Input[str]] = None,
            hide_tags: Optional[pulumi.Input[bool]] = None,
            logo: Optional[pulumi.Input[str]] = None,
            paginate: Optional[pulumi.Input[bool]] = None,
            pagination_rate: Optional[pulumi.Input[int]] = None,
            refresh_rate: Optional[pulumi.Input[int]] = None,
            tags: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
            width: Optional[pulumi.Input[str]] = None) -> 'PublicDashboard':
        """
        Get an existing PublicDashboard resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _PublicDashboardState.__new__(_PublicDashboardState)

        __props__.__dict__["custom_domain"] = custom_domain
        __props__.__dict__["custom_url"] = custom_url
        __props__.__dict__["header"] = header
        __props__.__dict__["hide_tags"] = hide_tags
        __props__.__dict__["logo"] = logo
        __props__.__dict__["paginate"] = paginate
        __props__.__dict__["pagination_rate"] = pagination_rate
        __props__.__dict__["refresh_rate"] = refresh_rate
        __props__.__dict__["tags"] = tags
        __props__.__dict__["width"] = width
        return PublicDashboard(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="customDomain")
    def custom_domain(self) -> pulumi.Output[str]:
        return pulumi.get(self, "custom_domain")

    @property
    @pulumi.getter(name="customUrl")
    def custom_url(self) -> pulumi.Output[str]:
        return pulumi.get(self, "custom_url")

    @property
    @pulumi.getter
    def header(self) -> pulumi.Output[str]:
        return pulumi.get(self, "header")

    @property
    @pulumi.getter(name="hideTags")
    def hide_tags(self) -> pulumi.Output[bool]:
        return pulumi.get(self, "hide_tags")

    @property
    @pulumi.getter
    def logo(self) -> pulumi.Output[str]:
        return pulumi.get(self, "logo")

    @property
    @pulumi.getter
    def paginate(self) -> pulumi.Output[bool]:
        return pulumi.get(self, "paginate")

    @property
    @pulumi.getter(name="paginationRate")
    def pagination_rate(self) -> pulumi.Output[int]:
        return pulumi.get(self, "pagination_rate")

    @property
    @pulumi.getter(name="refreshRate")
    def refresh_rate(self) -> pulumi.Output[int]:
        return pulumi.get(self, "refresh_rate")

    @property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[str]]]:
        return pulumi.get(self, "tags")

    @property
    @pulumi.getter
    def width(self) -> pulumi.Output[Optional[str]]:
        return pulumi.get(self, "width")

