# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['SslMonitorArgs', 'SslMonitor']

@pulumi.input_type
class SslMonitorArgs:
    def __init__(__self__, *,
                 activated: pulumi.Input[_builtins.bool],
                 frequency: pulumi.Input[_builtins.int],
                 request: pulumi.Input['SslMonitorRequestArgs'],
                 alert_channel_subscriptions: Optional[pulumi.Input[Sequence[pulumi.Input['SslMonitorAlertChannelSubscriptionArgs']]]] = None,
                 alert_settings: Optional[pulumi.Input['SslMonitorAlertSettingsArgs']] = None,
                 degraded_response_time: Optional[pulumi.Input[_builtins.int]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 frequency_offset: Optional[pulumi.Input[_builtins.int]] = None,
                 group_id: Optional[pulumi.Input[_builtins.int]] = None,
                 group_order: Optional[pulumi.Input[_builtins.int]] = None,
                 locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 max_response_time: Optional[pulumi.Input[_builtins.int]] = None,
                 muted: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 private_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 retry_strategy: Optional[pulumi.Input['SslMonitorRetryStrategyArgs']] = None,
                 run_parallel: Optional[pulumi.Input[_builtins.bool]] = None,
                 runtime_id: Optional[pulumi.Input[_builtins.str]] = None,
                 should_fail: Optional[pulumi.Input[_builtins.bool]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 trigger_incident: Optional[pulumi.Input['SslMonitorTriggerIncidentArgs']] = None,
                 use_global_alert_settings: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        The set of arguments for constructing a SslMonitor resource.
        :param pulumi.Input[_builtins.bool] activated: Determines if the monitor is running or not. Possible values `true`, and `false`.
        :param pulumi.Input[_builtins.int] frequency: Controls how often the monitor should run. Defined in minutes. The allowed values are `0` (high frequency - use `frequency_offset` to define the actual frequency), `1` (1 minute), `2` (2 minutes), `5` (5 minutes), `10` (10 minutes), `15` (15 minutes), `30` (30 minutes), `60` (1 hour), `120` (2 hours), `180` (3 hours), `360` (6 hours), `720` (12 hours) and `1440` (24 hours).
        :param pulumi.Input['SslMonitorRequestArgs'] request: The parameters for the SSL connection.
        :param pulumi.Input[Sequence[pulumi.Input['SslMonitorAlertChannelSubscriptionArgs']]] alert_channel_subscriptions: An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing.
        :param pulumi.Input['SslMonitorAlertSettingsArgs'] alert_settings: Determines the alert escalation policy for the monitor.
        :param pulumi.Input[_builtins.int] degraded_response_time: The handshake time in milliseconds above which the monitor is considered degraded. Possible values are between 0 and 30000. (Default `10000`).
        :param pulumi.Input[_builtins.str] description: A description of the monitor.
        :param pulumi.Input[_builtins.int] frequency_offset: When `frequency` is `0` (high frequency), `frequency_offset` is required and it alone controls how often the monitor should run. Defined in seconds. The allowed values are `0` (disabled - use `frequency` to define the actual frequency), `10` (10 seconds), `20` (20 seconds) and `30` (30 seconds).
        :param pulumi.Input[_builtins.int] group_id: The id of the check group this monitor is part of.
        :param pulumi.Input[_builtins.int] group_order: The position of this monitor in a check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] locations: An array of one or more data center locations where to run this monitor. (Default ["us-east-1"])
        :param pulumi.Input[_builtins.int] max_response_time: The handshake time in milliseconds above which the monitor is considered failing. Must be greater than or equal to `degraded_response_time`. Possible values are between 0 and 30000. (Default `20000`).
        :param pulumi.Input[_builtins.bool] muted: Determines if any notifications will be sent out when a monitor fails/degrades/recovers.
        :param pulumi.Input[_builtins.str] name: The name of the monitor.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] private_locations: An array of one or more private locations slugs.
        :param pulumi.Input['SslMonitorRetryStrategyArgs'] retry_strategy: A strategy for retrying failed check/monitor runs.
        :param pulumi.Input[_builtins.bool] run_parallel: Determines if the monitor should run in all selected locations in parallel or round-robin.
        :param pulumi.Input[_builtins.str] runtime_id: The ID of the runtime to use for this monitor.
        :param pulumi.Input[_builtins.bool] should_fail: Allows to invert the behaviour of when a monitor is considered to fail.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: A list of tags for organizing and filtering checks and monitors.
        :param pulumi.Input['SslMonitorTriggerIncidentArgs'] trigger_incident: Create and resolve an incident based on the alert configuration. Useful for status page automation.
        :param pulumi.Input[_builtins.bool] use_global_alert_settings: When true, the account level alert settings will be used, not the alert setting defined on this monitor.
        """
        pulumi.set(__self__, "activated", activated)
        pulumi.set(__self__, "frequency", frequency)
        pulumi.set(__self__, "request", request)
        if alert_channel_subscriptions is not None:
            pulumi.set(__self__, "alert_channel_subscriptions", alert_channel_subscriptions)
        if alert_settings is not None:
            pulumi.set(__self__, "alert_settings", alert_settings)
        if degraded_response_time is not None:
            pulumi.set(__self__, "degraded_response_time", degraded_response_time)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if frequency_offset is not None:
            pulumi.set(__self__, "frequency_offset", frequency_offset)
        if group_id is not None:
            pulumi.set(__self__, "group_id", group_id)
        if group_order is not None:
            pulumi.set(__self__, "group_order", group_order)
        if locations is not None:
            pulumi.set(__self__, "locations", locations)
        if max_response_time is not None:
            pulumi.set(__self__, "max_response_time", max_response_time)
        if muted is not None:
            pulumi.set(__self__, "muted", muted)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if private_locations is not None:
            pulumi.set(__self__, "private_locations", private_locations)
        if retry_strategy is not None:
            pulumi.set(__self__, "retry_strategy", retry_strategy)
        if run_parallel is not None:
            pulumi.set(__self__, "run_parallel", run_parallel)
        if runtime_id is not None:
            pulumi.set(__self__, "runtime_id", runtime_id)
        if should_fail is not None:
            pulumi.set(__self__, "should_fail", should_fail)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if trigger_incident is not None:
            pulumi.set(__self__, "trigger_incident", trigger_incident)
        if use_global_alert_settings is not None:
            pulumi.set(__self__, "use_global_alert_settings", use_global_alert_settings)

    @_builtins.property
    @pulumi.getter
    def activated(self) -> pulumi.Input[_builtins.bool]:
        """
        Determines if the monitor is running or not. Possible values `true`, and `false`.
        """
        return pulumi.get(self, "activated")

    @activated.setter
    def activated(self, value: pulumi.Input[_builtins.bool]):
        pulumi.set(self, "activated", value)

    @_builtins.property
    @pulumi.getter
    def frequency(self) -> pulumi.Input[_builtins.int]:
        """
        Controls how often the monitor should run. Defined in minutes. The allowed values are `0` (high frequency - use `frequency_offset` to define the actual frequency), `1` (1 minute), `2` (2 minutes), `5` (5 minutes), `10` (10 minutes), `15` (15 minutes), `30` (30 minutes), `60` (1 hour), `120` (2 hours), `180` (3 hours), `360` (6 hours), `720` (12 hours) and `1440` (24 hours).
        """
        return pulumi.get(self, "frequency")

    @frequency.setter
    def frequency(self, value: pulumi.Input[_builtins.int]):
        pulumi.set(self, "frequency", value)

    @_builtins.property
    @pulumi.getter
    def request(self) -> pulumi.Input['SslMonitorRequestArgs']:
        """
        The parameters for the SSL connection.
        """
        return pulumi.get(self, "request")

    @request.setter
    def request(self, value: pulumi.Input['SslMonitorRequestArgs']):
        pulumi.set(self, "request", value)

    @_builtins.property
    @pulumi.getter(name="alertChannelSubscriptions")
    def alert_channel_subscriptions(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SslMonitorAlertChannelSubscriptionArgs']]]]:
        """
        An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing.
        """
        return pulumi.get(self, "alert_channel_subscriptions")

    @alert_channel_subscriptions.setter
    def alert_channel_subscriptions(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SslMonitorAlertChannelSubscriptionArgs']]]]):
        pulumi.set(self, "alert_channel_subscriptions", value)

    @_builtins.property
    @pulumi.getter(name="alertSettings")
    def alert_settings(self) -> Optional[pulumi.Input['SslMonitorAlertSettingsArgs']]:
        """
        Determines the alert escalation policy for the monitor.
        """
        return pulumi.get(self, "alert_settings")

    @alert_settings.setter
    def alert_settings(self, value: Optional[pulumi.Input['SslMonitorAlertSettingsArgs']]):
        pulumi.set(self, "alert_settings", value)

    @_builtins.property
    @pulumi.getter(name="degradedResponseTime")
    def degraded_response_time(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The handshake time in milliseconds above which the monitor is considered degraded. Possible values are between 0 and 30000. (Default `10000`).
        """
        return pulumi.get(self, "degraded_response_time")

    @degraded_response_time.setter
    def degraded_response_time(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "degraded_response_time", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A description of the monitor.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="frequencyOffset")
    def frequency_offset(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        When `frequency` is `0` (high frequency), `frequency_offset` is required and it alone controls how often the monitor should run. Defined in seconds. The allowed values are `0` (disabled - use `frequency` to define the actual frequency), `10` (10 seconds), `20` (20 seconds) and `30` (30 seconds).
        """
        return pulumi.get(self, "frequency_offset")

    @frequency_offset.setter
    def frequency_offset(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "frequency_offset", value)

    @_builtins.property
    @pulumi.getter(name="groupId")
    def group_id(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The id of the check group this monitor is part of.
        """
        return pulumi.get(self, "group_id")

    @group_id.setter
    def group_id(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "group_id", value)

    @_builtins.property
    @pulumi.getter(name="groupOrder")
    def group_order(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The position of this monitor in a check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
        """
        return pulumi.get(self, "group_order")

    @group_order.setter
    def group_order(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "group_order", value)

    @_builtins.property
    @pulumi.getter
    def locations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        An array of one or more data center locations where to run this monitor. (Default ["us-east-1"])
        """
        return pulumi.get(self, "locations")

    @locations.setter
    def locations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "locations", value)

    @_builtins.property
    @pulumi.getter(name="maxResponseTime")
    def max_response_time(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The handshake time in milliseconds above which the monitor is considered failing. Must be greater than or equal to `degraded_response_time`. Possible values are between 0 and 30000. (Default `20000`).
        """
        return pulumi.get(self, "max_response_time")

    @max_response_time.setter
    def max_response_time(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "max_response_time", value)

    @_builtins.property
    @pulumi.getter
    def muted(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Determines if any notifications will be sent out when a monitor fails/degrades/recovers.
        """
        return pulumi.get(self, "muted")

    @muted.setter
    def muted(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "muted", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the monitor.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="privateLocations")
    def private_locations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        An array of one or more private locations slugs.
        """
        return pulumi.get(self, "private_locations")

    @private_locations.setter
    def private_locations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "private_locations", value)

    @_builtins.property
    @pulumi.getter(name="retryStrategy")
    def retry_strategy(self) -> Optional[pulumi.Input['SslMonitorRetryStrategyArgs']]:
        """
        A strategy for retrying failed check/monitor runs.
        """
        return pulumi.get(self, "retry_strategy")

    @retry_strategy.setter
    def retry_strategy(self, value: Optional[pulumi.Input['SslMonitorRetryStrategyArgs']]):
        pulumi.set(self, "retry_strategy", value)

    @_builtins.property
    @pulumi.getter(name="runParallel")
    def run_parallel(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Determines if the monitor should run in all selected locations in parallel or round-robin.
        """
        return pulumi.get(self, "run_parallel")

    @run_parallel.setter
    def run_parallel(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "run_parallel", value)

    @_builtins.property
    @pulumi.getter(name="runtimeId")
    def runtime_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the runtime to use for this monitor.
        """
        return pulumi.get(self, "runtime_id")

    @runtime_id.setter
    def runtime_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "runtime_id", value)

    @_builtins.property
    @pulumi.getter(name="shouldFail")
    def should_fail(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Allows to invert the behaviour of when a monitor is considered to fail.
        """
        return pulumi.get(self, "should_fail")

    @should_fail.setter
    def should_fail(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "should_fail", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        A list of tags for organizing and filtering checks and monitors.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="triggerIncident")
    def trigger_incident(self) -> Optional[pulumi.Input['SslMonitorTriggerIncidentArgs']]:
        """
        Create and resolve an incident based on the alert configuration. Useful for status page automation.
        """
        return pulumi.get(self, "trigger_incident")

    @trigger_incident.setter
    def trigger_incident(self, value: Optional[pulumi.Input['SslMonitorTriggerIncidentArgs']]):
        pulumi.set(self, "trigger_incident", value)

    @_builtins.property
    @pulumi.getter(name="useGlobalAlertSettings")
    def use_global_alert_settings(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        When true, the account level alert settings will be used, not the alert setting defined on this monitor.
        """
        return pulumi.get(self, "use_global_alert_settings")

    @use_global_alert_settings.setter
    def use_global_alert_settings(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "use_global_alert_settings", value)


@pulumi.input_type
class _SslMonitorState:
    def __init__(__self__, *,
                 activated: Optional[pulumi.Input[_builtins.bool]] = None,
                 alert_channel_subscriptions: Optional[pulumi.Input[Sequence[pulumi.Input['SslMonitorAlertChannelSubscriptionArgs']]]] = None,
                 alert_settings: Optional[pulumi.Input['SslMonitorAlertSettingsArgs']] = None,
                 degraded_response_time: Optional[pulumi.Input[_builtins.int]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 frequency: Optional[pulumi.Input[_builtins.int]] = None,
                 frequency_offset: Optional[pulumi.Input[_builtins.int]] = None,
                 group_id: Optional[pulumi.Input[_builtins.int]] = None,
                 group_order: Optional[pulumi.Input[_builtins.int]] = None,
                 locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 max_response_time: Optional[pulumi.Input[_builtins.int]] = None,
                 muted: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 private_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 request: Optional[pulumi.Input['SslMonitorRequestArgs']] = None,
                 retry_strategy: Optional[pulumi.Input['SslMonitorRetryStrategyArgs']] = None,
                 run_parallel: Optional[pulumi.Input[_builtins.bool]] = None,
                 runtime_id: Optional[pulumi.Input[_builtins.str]] = None,
                 should_fail: Optional[pulumi.Input[_builtins.bool]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 trigger_incident: Optional[pulumi.Input['SslMonitorTriggerIncidentArgs']] = None,
                 use_global_alert_settings: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        Input properties used for looking up and filtering SslMonitor resources.
        :param pulumi.Input[_builtins.bool] activated: Determines if the monitor is running or not. Possible values `true`, and `false`.
        :param pulumi.Input[Sequence[pulumi.Input['SslMonitorAlertChannelSubscriptionArgs']]] alert_channel_subscriptions: An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing.
        :param pulumi.Input['SslMonitorAlertSettingsArgs'] alert_settings: Determines the alert escalation policy for the monitor.
        :param pulumi.Input[_builtins.int] degraded_response_time: The handshake time in milliseconds above which the monitor is considered degraded. Possible values are between 0 and 30000. (Default `10000`).
        :param pulumi.Input[_builtins.str] description: A description of the monitor.
        :param pulumi.Input[_builtins.int] frequency: Controls how often the monitor should run. Defined in minutes. The allowed values are `0` (high frequency - use `frequency_offset` to define the actual frequency), `1` (1 minute), `2` (2 minutes), `5` (5 minutes), `10` (10 minutes), `15` (15 minutes), `30` (30 minutes), `60` (1 hour), `120` (2 hours), `180` (3 hours), `360` (6 hours), `720` (12 hours) and `1440` (24 hours).
        :param pulumi.Input[_builtins.int] frequency_offset: When `frequency` is `0` (high frequency), `frequency_offset` is required and it alone controls how often the monitor should run. Defined in seconds. The allowed values are `0` (disabled - use `frequency` to define the actual frequency), `10` (10 seconds), `20` (20 seconds) and `30` (30 seconds).
        :param pulumi.Input[_builtins.int] group_id: The id of the check group this monitor is part of.
        :param pulumi.Input[_builtins.int] group_order: The position of this monitor in a check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] locations: An array of one or more data center locations where to run this monitor. (Default ["us-east-1"])
        :param pulumi.Input[_builtins.int] max_response_time: The handshake time in milliseconds above which the monitor is considered failing. Must be greater than or equal to `degraded_response_time`. Possible values are between 0 and 30000. (Default `20000`).
        :param pulumi.Input[_builtins.bool] muted: Determines if any notifications will be sent out when a monitor fails/degrades/recovers.
        :param pulumi.Input[_builtins.str] name: The name of the monitor.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] private_locations: An array of one or more private locations slugs.
        :param pulumi.Input['SslMonitorRequestArgs'] request: The parameters for the SSL connection.
        :param pulumi.Input['SslMonitorRetryStrategyArgs'] retry_strategy: A strategy for retrying failed check/monitor runs.
        :param pulumi.Input[_builtins.bool] run_parallel: Determines if the monitor should run in all selected locations in parallel or round-robin.
        :param pulumi.Input[_builtins.str] runtime_id: The ID of the runtime to use for this monitor.
        :param pulumi.Input[_builtins.bool] should_fail: Allows to invert the behaviour of when a monitor is considered to fail.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: A list of tags for organizing and filtering checks and monitors.
        :param pulumi.Input['SslMonitorTriggerIncidentArgs'] trigger_incident: Create and resolve an incident based on the alert configuration. Useful for status page automation.
        :param pulumi.Input[_builtins.bool] use_global_alert_settings: When true, the account level alert settings will be used, not the alert setting defined on this monitor.
        """
        if activated is not None:
            pulumi.set(__self__, "activated", activated)
        if alert_channel_subscriptions is not None:
            pulumi.set(__self__, "alert_channel_subscriptions", alert_channel_subscriptions)
        if alert_settings is not None:
            pulumi.set(__self__, "alert_settings", alert_settings)
        if degraded_response_time is not None:
            pulumi.set(__self__, "degraded_response_time", degraded_response_time)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if frequency is not None:
            pulumi.set(__self__, "frequency", frequency)
        if frequency_offset is not None:
            pulumi.set(__self__, "frequency_offset", frequency_offset)
        if group_id is not None:
            pulumi.set(__self__, "group_id", group_id)
        if group_order is not None:
            pulumi.set(__self__, "group_order", group_order)
        if locations is not None:
            pulumi.set(__self__, "locations", locations)
        if max_response_time is not None:
            pulumi.set(__self__, "max_response_time", max_response_time)
        if muted is not None:
            pulumi.set(__self__, "muted", muted)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if private_locations is not None:
            pulumi.set(__self__, "private_locations", private_locations)
        if request is not None:
            pulumi.set(__self__, "request", request)
        if retry_strategy is not None:
            pulumi.set(__self__, "retry_strategy", retry_strategy)
        if run_parallel is not None:
            pulumi.set(__self__, "run_parallel", run_parallel)
        if runtime_id is not None:
            pulumi.set(__self__, "runtime_id", runtime_id)
        if should_fail is not None:
            pulumi.set(__self__, "should_fail", should_fail)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)
        if trigger_incident is not None:
            pulumi.set(__self__, "trigger_incident", trigger_incident)
        if use_global_alert_settings is not None:
            pulumi.set(__self__, "use_global_alert_settings", use_global_alert_settings)

    @_builtins.property
    @pulumi.getter
    def activated(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Determines if the monitor is running or not. Possible values `true`, and `false`.
        """
        return pulumi.get(self, "activated")

    @activated.setter
    def activated(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "activated", value)

    @_builtins.property
    @pulumi.getter(name="alertChannelSubscriptions")
    def alert_channel_subscriptions(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['SslMonitorAlertChannelSubscriptionArgs']]]]:
        """
        An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing.
        """
        return pulumi.get(self, "alert_channel_subscriptions")

    @alert_channel_subscriptions.setter
    def alert_channel_subscriptions(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['SslMonitorAlertChannelSubscriptionArgs']]]]):
        pulumi.set(self, "alert_channel_subscriptions", value)

    @_builtins.property
    @pulumi.getter(name="alertSettings")
    def alert_settings(self) -> Optional[pulumi.Input['SslMonitorAlertSettingsArgs']]:
        """
        Determines the alert escalation policy for the monitor.
        """
        return pulumi.get(self, "alert_settings")

    @alert_settings.setter
    def alert_settings(self, value: Optional[pulumi.Input['SslMonitorAlertSettingsArgs']]):
        pulumi.set(self, "alert_settings", value)

    @_builtins.property
    @pulumi.getter(name="degradedResponseTime")
    def degraded_response_time(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The handshake time in milliseconds above which the monitor is considered degraded. Possible values are between 0 and 30000. (Default `10000`).
        """
        return pulumi.get(self, "degraded_response_time")

    @degraded_response_time.setter
    def degraded_response_time(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "degraded_response_time", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A description of the monitor.
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def frequency(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Controls how often the monitor should run. Defined in minutes. The allowed values are `0` (high frequency - use `frequency_offset` to define the actual frequency), `1` (1 minute), `2` (2 minutes), `5` (5 minutes), `10` (10 minutes), `15` (15 minutes), `30` (30 minutes), `60` (1 hour), `120` (2 hours), `180` (3 hours), `360` (6 hours), `720` (12 hours) and `1440` (24 hours).
        """
        return pulumi.get(self, "frequency")

    @frequency.setter
    def frequency(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "frequency", value)

    @_builtins.property
    @pulumi.getter(name="frequencyOffset")
    def frequency_offset(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        When `frequency` is `0` (high frequency), `frequency_offset` is required and it alone controls how often the monitor should run. Defined in seconds. The allowed values are `0` (disabled - use `frequency` to define the actual frequency), `10` (10 seconds), `20` (20 seconds) and `30` (30 seconds).
        """
        return pulumi.get(self, "frequency_offset")

    @frequency_offset.setter
    def frequency_offset(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "frequency_offset", value)

    @_builtins.property
    @pulumi.getter(name="groupId")
    def group_id(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The id of the check group this monitor is part of.
        """
        return pulumi.get(self, "group_id")

    @group_id.setter
    def group_id(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "group_id", value)

    @_builtins.property
    @pulumi.getter(name="groupOrder")
    def group_order(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The position of this monitor in a check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
        """
        return pulumi.get(self, "group_order")

    @group_order.setter
    def group_order(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "group_order", value)

    @_builtins.property
    @pulumi.getter
    def locations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        An array of one or more data center locations where to run this monitor. (Default ["us-east-1"])
        """
        return pulumi.get(self, "locations")

    @locations.setter
    def locations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "locations", value)

    @_builtins.property
    @pulumi.getter(name="maxResponseTime")
    def max_response_time(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        The handshake time in milliseconds above which the monitor is considered failing. Must be greater than or equal to `degraded_response_time`. Possible values are between 0 and 30000. (Default `20000`).
        """
        return pulumi.get(self, "max_response_time")

    @max_response_time.setter
    def max_response_time(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "max_response_time", value)

    @_builtins.property
    @pulumi.getter
    def muted(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Determines if any notifications will be sent out when a monitor fails/degrades/recovers.
        """
        return pulumi.get(self, "muted")

    @muted.setter
    def muted(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "muted", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the monitor.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="privateLocations")
    def private_locations(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        An array of one or more private locations slugs.
        """
        return pulumi.get(self, "private_locations")

    @private_locations.setter
    def private_locations(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "private_locations", value)

    @_builtins.property
    @pulumi.getter
    def request(self) -> Optional[pulumi.Input['SslMonitorRequestArgs']]:
        """
        The parameters for the SSL connection.
        """
        return pulumi.get(self, "request")

    @request.setter
    def request(self, value: Optional[pulumi.Input['SslMonitorRequestArgs']]):
        pulumi.set(self, "request", value)

    @_builtins.property
    @pulumi.getter(name="retryStrategy")
    def retry_strategy(self) -> Optional[pulumi.Input['SslMonitorRetryStrategyArgs']]:
        """
        A strategy for retrying failed check/monitor runs.
        """
        return pulumi.get(self, "retry_strategy")

    @retry_strategy.setter
    def retry_strategy(self, value: Optional[pulumi.Input['SslMonitorRetryStrategyArgs']]):
        pulumi.set(self, "retry_strategy", value)

    @_builtins.property
    @pulumi.getter(name="runParallel")
    def run_parallel(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Determines if the monitor should run in all selected locations in parallel or round-robin.
        """
        return pulumi.get(self, "run_parallel")

    @run_parallel.setter
    def run_parallel(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "run_parallel", value)

    @_builtins.property
    @pulumi.getter(name="runtimeId")
    def runtime_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the runtime to use for this monitor.
        """
        return pulumi.get(self, "runtime_id")

    @runtime_id.setter
    def runtime_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "runtime_id", value)

    @_builtins.property
    @pulumi.getter(name="shouldFail")
    def should_fail(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Allows to invert the behaviour of when a monitor is considered to fail.
        """
        return pulumi.get(self, "should_fail")

    @should_fail.setter
    def should_fail(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "should_fail", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        A list of tags for organizing and filtering checks and monitors.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter(name="triggerIncident")
    def trigger_incident(self) -> Optional[pulumi.Input['SslMonitorTriggerIncidentArgs']]:
        """
        Create and resolve an incident based on the alert configuration. Useful for status page automation.
        """
        return pulumi.get(self, "trigger_incident")

    @trigger_incident.setter
    def trigger_incident(self, value: Optional[pulumi.Input['SslMonitorTriggerIncidentArgs']]):
        pulumi.set(self, "trigger_incident", value)

    @_builtins.property
    @pulumi.getter(name="useGlobalAlertSettings")
    def use_global_alert_settings(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        When true, the account level alert settings will be used, not the alert setting defined on this monitor.
        """
        return pulumi.get(self, "use_global_alert_settings")

    @use_global_alert_settings.setter
    def use_global_alert_settings(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "use_global_alert_settings", value)


@pulumi.type_token("checkly:index/sslMonitor:SslMonitor")
class SslMonitor(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 activated: Optional[pulumi.Input[_builtins.bool]] = None,
                 alert_channel_subscriptions: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SslMonitorAlertChannelSubscriptionArgs', 'SslMonitorAlertChannelSubscriptionArgsDict']]]]] = None,
                 alert_settings: Optional[pulumi.Input[Union['SslMonitorAlertSettingsArgs', 'SslMonitorAlertSettingsArgsDict']]] = None,
                 degraded_response_time: Optional[pulumi.Input[_builtins.int]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 frequency: Optional[pulumi.Input[_builtins.int]] = None,
                 frequency_offset: Optional[pulumi.Input[_builtins.int]] = None,
                 group_id: Optional[pulumi.Input[_builtins.int]] = None,
                 group_order: Optional[pulumi.Input[_builtins.int]] = None,
                 locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 max_response_time: Optional[pulumi.Input[_builtins.int]] = None,
                 muted: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 private_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 request: Optional[pulumi.Input[Union['SslMonitorRequestArgs', 'SslMonitorRequestArgsDict']]] = None,
                 retry_strategy: Optional[pulumi.Input[Union['SslMonitorRetryStrategyArgs', 'SslMonitorRetryStrategyArgsDict']]] = None,
                 run_parallel: Optional[pulumi.Input[_builtins.bool]] = None,
                 runtime_id: Optional[pulumi.Input[_builtins.str]] = None,
                 should_fail: Optional[pulumi.Input[_builtins.bool]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 trigger_incident: Optional[pulumi.Input[Union['SslMonitorTriggerIncidentArgs', 'SslMonitorTriggerIncidentArgsDict']]] = None,
                 use_global_alert_settings: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        """
        SSL monitors check the TLS certificate of a host and alert before it expires or violates a security baseline.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_checkly as checkly

        # Basic SSL/TLS certificate monitor
        example_ssl_monitor = checkly.SslMonitor("example-ssl-monitor",
            name="Example SSL monitor",
            activated=True,
            should_fail=False,
            frequency=60,
            use_global_alert_settings=True,
            locations=["us-west-1"],
            request={
                "hostname": "api.checklyhq.com",
                "port": 443,
                "alert_days_before_expiry": 30,
            })
        # A more complex example with response-time thresholds, a custom security
        # baseline and certificate assertions
        example_ssl_monitor_2 = checkly.SslMonitor("example-ssl-monitor-2",
            name="Example SSL monitor 2",
            activated=True,
            should_fail=False,
            frequency=60,
            degraded_response_time=3000,
            max_response_time=10000,
            locations=[
                "us-west-1",
                "eu-central-1",
            ],
            alert_settings={
                "escalation_type": "RUN_BASED",
                "run_based_escalations": [{
                    "failed_run_threshold": 1,
                }],
                "reminders": [{
                    "amount": 1,
                }],
            },
            request={
                "hostname": "api.checklyhq.com",
                "port": 443,
                "server_name": "api.checklyhq.com",
                "ip_family": "IPv4",
                "skip_chain_validation": False,
                "handshake_timeout_ms": 10000,
                "alert_days_before_expiry": 20,
                "security_baseline": {
                    "min_tls_version": {
                        "value": "TLS1.2",
                        "severity": "fail",
                    },
                    "min_key_size_bits": {
                        "value": 2048,
                        "severity": "fail",
                    },
                },
                "client_certificate": {
                    "mode": "account_default",
                },
                "assertions": [
                    {
                        "source": "CERTIFICATE",
                        "property": "daysUntilExpiry",
                        "comparison": "GREATER_THAN",
                        "target": "14",
                    },
                    {
                        "source": "CONNECTION",
                        "property": "hostnameVerified",
                        "comparison": "EQUALS",
                        "target": "true",
                    },
                ],
            })
        ```

        ## Assertion Reference

        Each `assertion` block has the shape `{ source, property, comparison, target }`. SSL assertions use a property-scoped grammar: for the `CERTIFICATE` and `CONNECTION` sources, `property` selects the fact being asserted, and that property determines which comparisons are allowed. These rules are enforced by the Checkly API at apply time.

        ### Source `CERTIFICATE`

        `property` is required and must be one of the following.

        | `property` | Value type | Allowed `comparison` values | Notes |
        |---|---|---|---|
        | `daysUntilExpiry` | number | `EQUALS`, `NOT_EQUALS`, `GREATER_THAN`, `LESS_THAN` | Days until the certificate expires. |
        | `keySizeBits` | number | `EQUALS`, `NOT_EQUALS`, `GREATER_THAN`, `LESS_THAN` | Public key size in bits. |
        | `subjectCN` | string | `EQUALS`, `NOT_EQUALS`, `CONTAINS`, `NOT_CONTAINS` | Subject common name. |
        | `issuerCN` | string | `EQUALS`, `NOT_EQUALS`, `CONTAINS`, `NOT_CONTAINS` | Issuer common name. |
        | `serialNumber` | string | `EQUALS`, `NOT_EQUALS` | |
        | `fingerprintSha256` | string | `EQUALS`, `NOT_EQUALS` | |
        | `issuerFingerprintSha256` | string | `EQUALS`, `NOT_EQUALS` | |
        | `keyAlgorithm` | string | `EQUALS`, `NOT_EQUALS` | |
        | `signatureAlgorithm` | string | `EQUALS`, `NOT_EQUALS` | e.g. `SHA256-RSA`, `ECDSA-SHA256`, `Ed25519`. |
        | `sans` | list of strings | `CONTAINS`, `NOT_CONTAINS` | Subject alternative names. |
        | `selfSigned` | boolean | `EQUALS` only | `target` is `"true"` or `"false"`. |
        | `isCA` | boolean | `EQUALS` only | `target` is `"true"` or `"false"`. |

        ### Source `CONNECTION`

        `property` is required and must be one of the following.

        | `property` | Value type | Allowed `comparison` values | Notes |
        |---|---|---|---|
        | `tlsVersion` | string (ordered) | `EQUALS`, `NOT_EQUALS`, `GREATER_THAN`, `LESS_THAN` | TLS versions compare in protocol order, e.g. `GREATER_THAN` `TLSv1.2` matches TLS 1.3. |
        | `cipherSuite` | string | `EQUALS`, `NOT_EQUALS`, `CONTAINS`, `NOT_CONTAINS` | IANA cipher suite name. |
        | `hostnameVerified` | boolean | `EQUALS` only | `target` is `"true"` or `"false"`. |
        | `chainTrusted` | boolean | `EQUALS` only | `target` is `"true"` or `"false"`. |
        | `ocspStapled` | boolean | `EQUALS` only | `target` is `"true"` or `"false"`. |
        | `ocspStatus` | string | `EQUALS`, `NOT_EQUALS` | |
        | `resolvedIp` | string | `EQUALS`, `NOT_EQUALS`, `CONTAINS`, `NOT_CONTAINS` | |

        ### Other sources

        | `source` | `property` | Allowed `comparison` values | `target` |
        |---|---|---|---|
        | `RESPONSE_TIME` | Must be empty. | `EQUALS`, `NOT_EQUALS`, `GREATER_THAN`, `LESS_THAN` | Handshake time in milliseconds, ≥ 0. |
        | `JSON_RESPONSE` | Required. A JSONPath expression over the check result (e.g. `$.certificate.keySizeBits`). | `EQUALS`, `NOT_EQUALS`, `IS_EMPTY`, `NOT_EMPTY`, `GREATER_THAN`, `LESS_THAN`, `CONTAINS`, `NOT_CONTAINS`, `IS_NULL`, `NOT_NULL` | Free-form string. |
        | `TEXT_RESPONSE` | Optional. A regular expression applied to the serialized response; empty matches the whole response. | `EQUALS`, `NOT_EQUALS`, `IS_EMPTY`, `NOT_EMPTY`, `CONTAINS`, `NOT_CONTAINS`, `GREATER_THAN`, `LESS_THAN` | Free-form string. |

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] activated: Determines if the monitor is running or not. Possible values `true`, and `false`.
        :param pulumi.Input[Sequence[pulumi.Input[Union['SslMonitorAlertChannelSubscriptionArgs', 'SslMonitorAlertChannelSubscriptionArgsDict']]]] alert_channel_subscriptions: An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing.
        :param pulumi.Input[Union['SslMonitorAlertSettingsArgs', 'SslMonitorAlertSettingsArgsDict']] alert_settings: Determines the alert escalation policy for the monitor.
        :param pulumi.Input[_builtins.int] degraded_response_time: The handshake time in milliseconds above which the monitor is considered degraded. Possible values are between 0 and 30000. (Default `10000`).
        :param pulumi.Input[_builtins.str] description: A description of the monitor.
        :param pulumi.Input[_builtins.int] frequency: Controls how often the monitor should run. Defined in minutes. The allowed values are `0` (high frequency - use `frequency_offset` to define the actual frequency), `1` (1 minute), `2` (2 minutes), `5` (5 minutes), `10` (10 minutes), `15` (15 minutes), `30` (30 minutes), `60` (1 hour), `120` (2 hours), `180` (3 hours), `360` (6 hours), `720` (12 hours) and `1440` (24 hours).
        :param pulumi.Input[_builtins.int] frequency_offset: When `frequency` is `0` (high frequency), `frequency_offset` is required and it alone controls how often the monitor should run. Defined in seconds. The allowed values are `0` (disabled - use `frequency` to define the actual frequency), `10` (10 seconds), `20` (20 seconds) and `30` (30 seconds).
        :param pulumi.Input[_builtins.int] group_id: The id of the check group this monitor is part of.
        :param pulumi.Input[_builtins.int] group_order: The position of this monitor in a check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] locations: An array of one or more data center locations where to run this monitor. (Default ["us-east-1"])
        :param pulumi.Input[_builtins.int] max_response_time: The handshake time in milliseconds above which the monitor is considered failing. Must be greater than or equal to `degraded_response_time`. Possible values are between 0 and 30000. (Default `20000`).
        :param pulumi.Input[_builtins.bool] muted: Determines if any notifications will be sent out when a monitor fails/degrades/recovers.
        :param pulumi.Input[_builtins.str] name: The name of the monitor.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] private_locations: An array of one or more private locations slugs.
        :param pulumi.Input[Union['SslMonitorRequestArgs', 'SslMonitorRequestArgsDict']] request: The parameters for the SSL connection.
        :param pulumi.Input[Union['SslMonitorRetryStrategyArgs', 'SslMonitorRetryStrategyArgsDict']] retry_strategy: A strategy for retrying failed check/monitor runs.
        :param pulumi.Input[_builtins.bool] run_parallel: Determines if the monitor should run in all selected locations in parallel or round-robin.
        :param pulumi.Input[_builtins.str] runtime_id: The ID of the runtime to use for this monitor.
        :param pulumi.Input[_builtins.bool] should_fail: Allows to invert the behaviour of when a monitor is considered to fail.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: A list of tags for organizing and filtering checks and monitors.
        :param pulumi.Input[Union['SslMonitorTriggerIncidentArgs', 'SslMonitorTriggerIncidentArgsDict']] trigger_incident: Create and resolve an incident based on the alert configuration. Useful for status page automation.
        :param pulumi.Input[_builtins.bool] use_global_alert_settings: When true, the account level alert settings will be used, not the alert setting defined on this monitor.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: SslMonitorArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        SSL monitors check the TLS certificate of a host and alert before it expires or violates a security baseline.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_checkly as checkly

        # Basic SSL/TLS certificate monitor
        example_ssl_monitor = checkly.SslMonitor("example-ssl-monitor",
            name="Example SSL monitor",
            activated=True,
            should_fail=False,
            frequency=60,
            use_global_alert_settings=True,
            locations=["us-west-1"],
            request={
                "hostname": "api.checklyhq.com",
                "port": 443,
                "alert_days_before_expiry": 30,
            })
        # A more complex example with response-time thresholds, a custom security
        # baseline and certificate assertions
        example_ssl_monitor_2 = checkly.SslMonitor("example-ssl-monitor-2",
            name="Example SSL monitor 2",
            activated=True,
            should_fail=False,
            frequency=60,
            degraded_response_time=3000,
            max_response_time=10000,
            locations=[
                "us-west-1",
                "eu-central-1",
            ],
            alert_settings={
                "escalation_type": "RUN_BASED",
                "run_based_escalations": [{
                    "failed_run_threshold": 1,
                }],
                "reminders": [{
                    "amount": 1,
                }],
            },
            request={
                "hostname": "api.checklyhq.com",
                "port": 443,
                "server_name": "api.checklyhq.com",
                "ip_family": "IPv4",
                "skip_chain_validation": False,
                "handshake_timeout_ms": 10000,
                "alert_days_before_expiry": 20,
                "security_baseline": {
                    "min_tls_version": {
                        "value": "TLS1.2",
                        "severity": "fail",
                    },
                    "min_key_size_bits": {
                        "value": 2048,
                        "severity": "fail",
                    },
                },
                "client_certificate": {
                    "mode": "account_default",
                },
                "assertions": [
                    {
                        "source": "CERTIFICATE",
                        "property": "daysUntilExpiry",
                        "comparison": "GREATER_THAN",
                        "target": "14",
                    },
                    {
                        "source": "CONNECTION",
                        "property": "hostnameVerified",
                        "comparison": "EQUALS",
                        "target": "true",
                    },
                ],
            })
        ```

        ## Assertion Reference

        Each `assertion` block has the shape `{ source, property, comparison, target }`. SSL assertions use a property-scoped grammar: for the `CERTIFICATE` and `CONNECTION` sources, `property` selects the fact being asserted, and that property determines which comparisons are allowed. These rules are enforced by the Checkly API at apply time.

        ### Source `CERTIFICATE`

        `property` is required and must be one of the following.

        | `property` | Value type | Allowed `comparison` values | Notes |
        |---|---|---|---|
        | `daysUntilExpiry` | number | `EQUALS`, `NOT_EQUALS`, `GREATER_THAN`, `LESS_THAN` | Days until the certificate expires. |
        | `keySizeBits` | number | `EQUALS`, `NOT_EQUALS`, `GREATER_THAN`, `LESS_THAN` | Public key size in bits. |
        | `subjectCN` | string | `EQUALS`, `NOT_EQUALS`, `CONTAINS`, `NOT_CONTAINS` | Subject common name. |
        | `issuerCN` | string | `EQUALS`, `NOT_EQUALS`, `CONTAINS`, `NOT_CONTAINS` | Issuer common name. |
        | `serialNumber` | string | `EQUALS`, `NOT_EQUALS` | |
        | `fingerprintSha256` | string | `EQUALS`, `NOT_EQUALS` | |
        | `issuerFingerprintSha256` | string | `EQUALS`, `NOT_EQUALS` | |
        | `keyAlgorithm` | string | `EQUALS`, `NOT_EQUALS` | |
        | `signatureAlgorithm` | string | `EQUALS`, `NOT_EQUALS` | e.g. `SHA256-RSA`, `ECDSA-SHA256`, `Ed25519`. |
        | `sans` | list of strings | `CONTAINS`, `NOT_CONTAINS` | Subject alternative names. |
        | `selfSigned` | boolean | `EQUALS` only | `target` is `"true"` or `"false"`. |
        | `isCA` | boolean | `EQUALS` only | `target` is `"true"` or `"false"`. |

        ### Source `CONNECTION`

        `property` is required and must be one of the following.

        | `property` | Value type | Allowed `comparison` values | Notes |
        |---|---|---|---|
        | `tlsVersion` | string (ordered) | `EQUALS`, `NOT_EQUALS`, `GREATER_THAN`, `LESS_THAN` | TLS versions compare in protocol order, e.g. `GREATER_THAN` `TLSv1.2` matches TLS 1.3. |
        | `cipherSuite` | string | `EQUALS`, `NOT_EQUALS`, `CONTAINS`, `NOT_CONTAINS` | IANA cipher suite name. |
        | `hostnameVerified` | boolean | `EQUALS` only | `target` is `"true"` or `"false"`. |
        | `chainTrusted` | boolean | `EQUALS` only | `target` is `"true"` or `"false"`. |
        | `ocspStapled` | boolean | `EQUALS` only | `target` is `"true"` or `"false"`. |
        | `ocspStatus` | string | `EQUALS`, `NOT_EQUALS` | |
        | `resolvedIp` | string | `EQUALS`, `NOT_EQUALS`, `CONTAINS`, `NOT_CONTAINS` | |

        ### Other sources

        | `source` | `property` | Allowed `comparison` values | `target` |
        |---|---|---|---|
        | `RESPONSE_TIME` | Must be empty. | `EQUALS`, `NOT_EQUALS`, `GREATER_THAN`, `LESS_THAN` | Handshake time in milliseconds, ≥ 0. |
        | `JSON_RESPONSE` | Required. A JSONPath expression over the check result (e.g. `$.certificate.keySizeBits`). | `EQUALS`, `NOT_EQUALS`, `IS_EMPTY`, `NOT_EMPTY`, `GREATER_THAN`, `LESS_THAN`, `CONTAINS`, `NOT_CONTAINS`, `IS_NULL`, `NOT_NULL` | Free-form string. |
        | `TEXT_RESPONSE` | Optional. A regular expression applied to the serialized response; empty matches the whole response. | `EQUALS`, `NOT_EQUALS`, `IS_EMPTY`, `NOT_EMPTY`, `CONTAINS`, `NOT_CONTAINS`, `GREATER_THAN`, `LESS_THAN` | Free-form string. |

        :param str resource_name: The name of the resource.
        :param SslMonitorArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(SslMonitorArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 activated: Optional[pulumi.Input[_builtins.bool]] = None,
                 alert_channel_subscriptions: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SslMonitorAlertChannelSubscriptionArgs', 'SslMonitorAlertChannelSubscriptionArgsDict']]]]] = None,
                 alert_settings: Optional[pulumi.Input[Union['SslMonitorAlertSettingsArgs', 'SslMonitorAlertSettingsArgsDict']]] = None,
                 degraded_response_time: Optional[pulumi.Input[_builtins.int]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 frequency: Optional[pulumi.Input[_builtins.int]] = None,
                 frequency_offset: Optional[pulumi.Input[_builtins.int]] = None,
                 group_id: Optional[pulumi.Input[_builtins.int]] = None,
                 group_order: Optional[pulumi.Input[_builtins.int]] = None,
                 locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 max_response_time: Optional[pulumi.Input[_builtins.int]] = None,
                 muted: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 private_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 request: Optional[pulumi.Input[Union['SslMonitorRequestArgs', 'SslMonitorRequestArgsDict']]] = None,
                 retry_strategy: Optional[pulumi.Input[Union['SslMonitorRetryStrategyArgs', 'SslMonitorRetryStrategyArgsDict']]] = None,
                 run_parallel: Optional[pulumi.Input[_builtins.bool]] = None,
                 runtime_id: Optional[pulumi.Input[_builtins.str]] = None,
                 should_fail: Optional[pulumi.Input[_builtins.bool]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 trigger_incident: Optional[pulumi.Input[Union['SslMonitorTriggerIncidentArgs', 'SslMonitorTriggerIncidentArgsDict']]] = None,
                 use_global_alert_settings: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = SslMonitorArgs.__new__(SslMonitorArgs)

            if activated is None and not opts.urn:
                raise TypeError("Missing required property 'activated'")
            __props__.__dict__["activated"] = activated
            __props__.__dict__["alert_channel_subscriptions"] = alert_channel_subscriptions
            __props__.__dict__["alert_settings"] = alert_settings
            __props__.__dict__["degraded_response_time"] = degraded_response_time
            __props__.__dict__["description"] = description
            if frequency is None and not opts.urn:
                raise TypeError("Missing required property 'frequency'")
            __props__.__dict__["frequency"] = frequency
            __props__.__dict__["frequency_offset"] = frequency_offset
            __props__.__dict__["group_id"] = group_id
            __props__.__dict__["group_order"] = group_order
            __props__.__dict__["locations"] = locations
            __props__.__dict__["max_response_time"] = max_response_time
            __props__.__dict__["muted"] = muted
            __props__.__dict__["name"] = name
            __props__.__dict__["private_locations"] = private_locations
            if request is None and not opts.urn:
                raise TypeError("Missing required property 'request'")
            __props__.__dict__["request"] = request
            __props__.__dict__["retry_strategy"] = retry_strategy
            __props__.__dict__["run_parallel"] = run_parallel
            __props__.__dict__["runtime_id"] = runtime_id
            __props__.__dict__["should_fail"] = should_fail
            __props__.__dict__["tags"] = tags
            __props__.__dict__["trigger_incident"] = trigger_incident
            __props__.__dict__["use_global_alert_settings"] = use_global_alert_settings
        super(SslMonitor, __self__).__init__(
            'checkly:index/sslMonitor:SslMonitor',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            activated: Optional[pulumi.Input[_builtins.bool]] = None,
            alert_channel_subscriptions: Optional[pulumi.Input[Sequence[pulumi.Input[Union['SslMonitorAlertChannelSubscriptionArgs', 'SslMonitorAlertChannelSubscriptionArgsDict']]]]] = None,
            alert_settings: Optional[pulumi.Input[Union['SslMonitorAlertSettingsArgs', 'SslMonitorAlertSettingsArgsDict']]] = None,
            degraded_response_time: Optional[pulumi.Input[_builtins.int]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            frequency: Optional[pulumi.Input[_builtins.int]] = None,
            frequency_offset: Optional[pulumi.Input[_builtins.int]] = None,
            group_id: Optional[pulumi.Input[_builtins.int]] = None,
            group_order: Optional[pulumi.Input[_builtins.int]] = None,
            locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            max_response_time: Optional[pulumi.Input[_builtins.int]] = None,
            muted: Optional[pulumi.Input[_builtins.bool]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            private_locations: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            request: Optional[pulumi.Input[Union['SslMonitorRequestArgs', 'SslMonitorRequestArgsDict']]] = None,
            retry_strategy: Optional[pulumi.Input[Union['SslMonitorRetryStrategyArgs', 'SslMonitorRetryStrategyArgsDict']]] = None,
            run_parallel: Optional[pulumi.Input[_builtins.bool]] = None,
            runtime_id: Optional[pulumi.Input[_builtins.str]] = None,
            should_fail: Optional[pulumi.Input[_builtins.bool]] = None,
            tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            trigger_incident: Optional[pulumi.Input[Union['SslMonitorTriggerIncidentArgs', 'SslMonitorTriggerIncidentArgsDict']]] = None,
            use_global_alert_settings: Optional[pulumi.Input[_builtins.bool]] = None) -> 'SslMonitor':
        """
        Get an existing SslMonitor resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] activated: Determines if the monitor is running or not. Possible values `true`, and `false`.
        :param pulumi.Input[Sequence[pulumi.Input[Union['SslMonitorAlertChannelSubscriptionArgs', 'SslMonitorAlertChannelSubscriptionArgsDict']]]] alert_channel_subscriptions: An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing.
        :param pulumi.Input[Union['SslMonitorAlertSettingsArgs', 'SslMonitorAlertSettingsArgsDict']] alert_settings: Determines the alert escalation policy for the monitor.
        :param pulumi.Input[_builtins.int] degraded_response_time: The handshake time in milliseconds above which the monitor is considered degraded. Possible values are between 0 and 30000. (Default `10000`).
        :param pulumi.Input[_builtins.str] description: A description of the monitor.
        :param pulumi.Input[_builtins.int] frequency: Controls how often the monitor should run. Defined in minutes. The allowed values are `0` (high frequency - use `frequency_offset` to define the actual frequency), `1` (1 minute), `2` (2 minutes), `5` (5 minutes), `10` (10 minutes), `15` (15 minutes), `30` (30 minutes), `60` (1 hour), `120` (2 hours), `180` (3 hours), `360` (6 hours), `720` (12 hours) and `1440` (24 hours).
        :param pulumi.Input[_builtins.int] frequency_offset: When `frequency` is `0` (high frequency), `frequency_offset` is required and it alone controls how often the monitor should run. Defined in seconds. The allowed values are `0` (disabled - use `frequency` to define the actual frequency), `10` (10 seconds), `20` (20 seconds) and `30` (30 seconds).
        :param pulumi.Input[_builtins.int] group_id: The id of the check group this monitor is part of.
        :param pulumi.Input[_builtins.int] group_order: The position of this monitor in a check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] locations: An array of one or more data center locations where to run this monitor. (Default ["us-east-1"])
        :param pulumi.Input[_builtins.int] max_response_time: The handshake time in milliseconds above which the monitor is considered failing. Must be greater than or equal to `degraded_response_time`. Possible values are between 0 and 30000. (Default `20000`).
        :param pulumi.Input[_builtins.bool] muted: Determines if any notifications will be sent out when a monitor fails/degrades/recovers.
        :param pulumi.Input[_builtins.str] name: The name of the monitor.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] private_locations: An array of one or more private locations slugs.
        :param pulumi.Input[Union['SslMonitorRequestArgs', 'SslMonitorRequestArgsDict']] request: The parameters for the SSL connection.
        :param pulumi.Input[Union['SslMonitorRetryStrategyArgs', 'SslMonitorRetryStrategyArgsDict']] retry_strategy: A strategy for retrying failed check/monitor runs.
        :param pulumi.Input[_builtins.bool] run_parallel: Determines if the monitor should run in all selected locations in parallel or round-robin.
        :param pulumi.Input[_builtins.str] runtime_id: The ID of the runtime to use for this monitor.
        :param pulumi.Input[_builtins.bool] should_fail: Allows to invert the behaviour of when a monitor is considered to fail.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: A list of tags for organizing and filtering checks and monitors.
        :param pulumi.Input[Union['SslMonitorTriggerIncidentArgs', 'SslMonitorTriggerIncidentArgsDict']] trigger_incident: Create and resolve an incident based on the alert configuration. Useful for status page automation.
        :param pulumi.Input[_builtins.bool] use_global_alert_settings: When true, the account level alert settings will be used, not the alert setting defined on this monitor.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _SslMonitorState.__new__(_SslMonitorState)

        __props__.__dict__["activated"] = activated
        __props__.__dict__["alert_channel_subscriptions"] = alert_channel_subscriptions
        __props__.__dict__["alert_settings"] = alert_settings
        __props__.__dict__["degraded_response_time"] = degraded_response_time
        __props__.__dict__["description"] = description
        __props__.__dict__["frequency"] = frequency
        __props__.__dict__["frequency_offset"] = frequency_offset
        __props__.__dict__["group_id"] = group_id
        __props__.__dict__["group_order"] = group_order
        __props__.__dict__["locations"] = locations
        __props__.__dict__["max_response_time"] = max_response_time
        __props__.__dict__["muted"] = muted
        __props__.__dict__["name"] = name
        __props__.__dict__["private_locations"] = private_locations
        __props__.__dict__["request"] = request
        __props__.__dict__["retry_strategy"] = retry_strategy
        __props__.__dict__["run_parallel"] = run_parallel
        __props__.__dict__["runtime_id"] = runtime_id
        __props__.__dict__["should_fail"] = should_fail
        __props__.__dict__["tags"] = tags
        __props__.__dict__["trigger_incident"] = trigger_incident
        __props__.__dict__["use_global_alert_settings"] = use_global_alert_settings
        return SslMonitor(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def activated(self) -> pulumi.Output[_builtins.bool]:
        """
        Determines if the monitor is running or not. Possible values `true`, and `false`.
        """
        return pulumi.get(self, "activated")

    @_builtins.property
    @pulumi.getter(name="alertChannelSubscriptions")
    def alert_channel_subscriptions(self) -> pulumi.Output[Optional[Sequence['outputs.SslMonitorAlertChannelSubscription']]]:
        """
        An array of channel IDs and whether they're activated or not. If you don't set at least one alert channel subscription for your monitor, we won't be able to alert you even if it starts failing.
        """
        return pulumi.get(self, "alert_channel_subscriptions")

    @_builtins.property
    @pulumi.getter(name="alertSettings")
    def alert_settings(self) -> pulumi.Output['outputs.SslMonitorAlertSettings']:
        """
        Determines the alert escalation policy for the monitor.
        """
        return pulumi.get(self, "alert_settings")

    @_builtins.property
    @pulumi.getter(name="degradedResponseTime")
    def degraded_response_time(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        The handshake time in milliseconds above which the monitor is considered degraded. Possible values are between 0 and 30000. (Default `10000`).
        """
        return pulumi.get(self, "degraded_response_time")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        A description of the monitor.
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def frequency(self) -> pulumi.Output[_builtins.int]:
        """
        Controls how often the monitor should run. Defined in minutes. The allowed values are `0` (high frequency - use `frequency_offset` to define the actual frequency), `1` (1 minute), `2` (2 minutes), `5` (5 minutes), `10` (10 minutes), `15` (15 minutes), `30` (30 minutes), `60` (1 hour), `120` (2 hours), `180` (3 hours), `360` (6 hours), `720` (12 hours) and `1440` (24 hours).
        """
        return pulumi.get(self, "frequency")

    @_builtins.property
    @pulumi.getter(name="frequencyOffset")
    def frequency_offset(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        When `frequency` is `0` (high frequency), `frequency_offset` is required and it alone controls how often the monitor should run. Defined in seconds. The allowed values are `0` (disabled - use `frequency` to define the actual frequency), `10` (10 seconds), `20` (20 seconds) and `30` (30 seconds).
        """
        return pulumi.get(self, "frequency_offset")

    @_builtins.property
    @pulumi.getter(name="groupId")
    def group_id(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        The id of the check group this monitor is part of.
        """
        return pulumi.get(self, "group_id")

    @_builtins.property
    @pulumi.getter(name="groupOrder")
    def group_order(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        The position of this monitor in a check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
        """
        return pulumi.get(self, "group_order")

    @_builtins.property
    @pulumi.getter
    def locations(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        An array of one or more data center locations where to run this monitor. (Default ["us-east-1"])
        """
        return pulumi.get(self, "locations")

    @_builtins.property
    @pulumi.getter(name="maxResponseTime")
    def max_response_time(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        The handshake time in milliseconds above which the monitor is considered failing. Must be greater than or equal to `degraded_response_time`. Possible values are between 0 and 30000. (Default `20000`).
        """
        return pulumi.get(self, "max_response_time")

    @_builtins.property
    @pulumi.getter
    def muted(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Determines if any notifications will be sent out when a monitor fails/degrades/recovers.
        """
        return pulumi.get(self, "muted")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the monitor.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="privateLocations")
    def private_locations(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        An array of one or more private locations slugs.
        """
        return pulumi.get(self, "private_locations")

    @_builtins.property
    @pulumi.getter
    def request(self) -> pulumi.Output['outputs.SslMonitorRequest']:
        """
        The parameters for the SSL connection.
        """
        return pulumi.get(self, "request")

    @_builtins.property
    @pulumi.getter(name="retryStrategy")
    def retry_strategy(self) -> pulumi.Output['outputs.SslMonitorRetryStrategy']:
        """
        A strategy for retrying failed check/monitor runs.
        """
        return pulumi.get(self, "retry_strategy")

    @_builtins.property
    @pulumi.getter(name="runParallel")
    def run_parallel(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Determines if the monitor should run in all selected locations in parallel or round-robin.
        """
        return pulumi.get(self, "run_parallel")

    @_builtins.property
    @pulumi.getter(name="runtimeId")
    def runtime_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The ID of the runtime to use for this monitor.
        """
        return pulumi.get(self, "runtime_id")

    @_builtins.property
    @pulumi.getter(name="shouldFail")
    def should_fail(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Allows to invert the behaviour of when a monitor is considered to fail.
        """
        return pulumi.get(self, "should_fail")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        A list of tags for organizing and filtering checks and monitors.
        """
        return pulumi.get(self, "tags")

    @_builtins.property
    @pulumi.getter(name="triggerIncident")
    def trigger_incident(self) -> pulumi.Output[Optional['outputs.SslMonitorTriggerIncident']]:
        """
        Create and resolve an incident based on the alert configuration. Useful for status page automation.
        """
        return pulumi.get(self, "trigger_incident")

    @_builtins.property
    @pulumi.getter(name="useGlobalAlertSettings")
    def use_global_alert_settings(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        When true, the account level alert settings will be used, not the alert setting defined on this monitor.
        """
        return pulumi.get(self, "use_global_alert_settings")

