# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['StatusPageV3AutomationRuleArgs', 'StatusPageV3AutomationRule']

@pulumi.input_type
class StatusPageV3AutomationRuleArgs:
    def __init__(__self__, *,
                 first_update: pulumi.Input[_builtins.str],
                 last_update: pulumi.Input[_builtins.str],
                 status_page_id: pulumi.Input[_builtins.str],
                 tags: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 components: Optional[pulumi.Input[Sequence[pulumi.Input['StatusPageV3AutomationRuleComponentArgs']]]] = None,
                 cool_down_window_minutes: Optional[pulumi.Input[_builtins.int]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 notify_subscribers: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        The set of arguments for constructing a StatusPageV3AutomationRule resource.
        :param pulumi.Input[_builtins.str] first_update: Body of the status update that opens the incident.
        :param pulumi.Input[_builtins.str] last_update: Body of the status update that resolves the incident.
        :param pulumi.Input[_builtins.str] status_page_id: The ID of the v3 status page the rule belongs to.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: A failing check matches this rule when it, or its group, carries ANY of these tags. At least one tag is required.
        :param pulumi.Input[Sequence[pulumi.Input['StatusPageV3AutomationRuleComponentArgs']]] components: The components an automated incident impacts, with the impact each gets.
        :param pulumi.Input[_builtins.int] cool_down_window_minutes: Minimum minutes after an automated incident before this rule may open the next one. `0` disables the cool down. (Default `5`).
        :param pulumi.Input[_builtins.bool] enabled: A disabled rule never opens incidents. (Default `true`).
        :param pulumi.Input[_builtins.str] name: The name of the rule.
        :param pulumi.Input[_builtins.bool] notify_subscribers: Whether subscribers are notified of the automated updates. (Default `true`).
        """
        pulumi.set(__self__, "first_update", first_update)
        pulumi.set(__self__, "last_update", last_update)
        pulumi.set(__self__, "status_page_id", status_page_id)
        pulumi.set(__self__, "tags", tags)
        if components is not None:
            pulumi.set(__self__, "components", components)
        if cool_down_window_minutes is not None:
            pulumi.set(__self__, "cool_down_window_minutes", cool_down_window_minutes)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if notify_subscribers is not None:
            pulumi.set(__self__, "notify_subscribers", notify_subscribers)

    @_builtins.property
    @pulumi.getter(name="firstUpdate")
    def first_update(self) -> pulumi.Input[_builtins.str]:
        """
        Body of the status update that opens the incident.
        """
        return pulumi.get(self, "first_update")

    @first_update.setter
    def first_update(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "first_update", value)

    @_builtins.property
    @pulumi.getter(name="lastUpdate")
    def last_update(self) -> pulumi.Input[_builtins.str]:
        """
        Body of the status update that resolves the incident.
        """
        return pulumi.get(self, "last_update")

    @last_update.setter
    def last_update(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "last_update", value)

    @_builtins.property
    @pulumi.getter(name="statusPageId")
    def status_page_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the v3 status page the rule belongs to.
        """
        return pulumi.get(self, "status_page_id")

    @status_page_id.setter
    def status_page_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "status_page_id", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        A failing check matches this rule when it, or its group, carries ANY of these tags. At least one tag is required.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "tags", value)

    @_builtins.property
    @pulumi.getter
    def components(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['StatusPageV3AutomationRuleComponentArgs']]]]:
        """
        The components an automated incident impacts, with the impact each gets.
        """
        return pulumi.get(self, "components")

    @components.setter
    def components(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['StatusPageV3AutomationRuleComponentArgs']]]]):
        pulumi.set(self, "components", value)

    @_builtins.property
    @pulumi.getter(name="coolDownWindowMinutes")
    def cool_down_window_minutes(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Minimum minutes after an automated incident before this rule may open the next one. `0` disables the cool down. (Default `5`).
        """
        return pulumi.get(self, "cool_down_window_minutes")

    @cool_down_window_minutes.setter
    def cool_down_window_minutes(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "cool_down_window_minutes", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        A disabled rule never opens incidents. (Default `true`).
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the rule.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="notifySubscribers")
    def notify_subscribers(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether subscribers are notified of the automated updates. (Default `true`).
        """
        return pulumi.get(self, "notify_subscribers")

    @notify_subscribers.setter
    def notify_subscribers(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "notify_subscribers", value)


@pulumi.input_type
class _StatusPageV3AutomationRuleState:
    def __init__(__self__, *,
                 components: Optional[pulumi.Input[Sequence[pulumi.Input['StatusPageV3AutomationRuleComponentArgs']]]] = None,
                 cool_down_window_minutes: Optional[pulumi.Input[_builtins.int]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 first_update: Optional[pulumi.Input[_builtins.str]] = None,
                 last_update: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 notify_subscribers: Optional[pulumi.Input[_builtins.bool]] = None,
                 status_page_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        Input properties used for looking up and filtering StatusPageV3AutomationRule resources.
        :param pulumi.Input[Sequence[pulumi.Input['StatusPageV3AutomationRuleComponentArgs']]] components: The components an automated incident impacts, with the impact each gets.
        :param pulumi.Input[_builtins.int] cool_down_window_minutes: Minimum minutes after an automated incident before this rule may open the next one. `0` disables the cool down. (Default `5`).
        :param pulumi.Input[_builtins.bool] enabled: A disabled rule never opens incidents. (Default `true`).
        :param pulumi.Input[_builtins.str] first_update: Body of the status update that opens the incident.
        :param pulumi.Input[_builtins.str] last_update: Body of the status update that resolves the incident.
        :param pulumi.Input[_builtins.str] name: The name of the rule.
        :param pulumi.Input[_builtins.bool] notify_subscribers: Whether subscribers are notified of the automated updates. (Default `true`).
        :param pulumi.Input[_builtins.str] status_page_id: The ID of the v3 status page the rule belongs to.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: A failing check matches this rule when it, or its group, carries ANY of these tags. At least one tag is required.
        """
        if components is not None:
            pulumi.set(__self__, "components", components)
        if cool_down_window_minutes is not None:
            pulumi.set(__self__, "cool_down_window_minutes", cool_down_window_minutes)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if first_update is not None:
            pulumi.set(__self__, "first_update", first_update)
        if last_update is not None:
            pulumi.set(__self__, "last_update", last_update)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if notify_subscribers is not None:
            pulumi.set(__self__, "notify_subscribers", notify_subscribers)
        if status_page_id is not None:
            pulumi.set(__self__, "status_page_id", status_page_id)
        if tags is not None:
            pulumi.set(__self__, "tags", tags)

    @_builtins.property
    @pulumi.getter
    def components(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['StatusPageV3AutomationRuleComponentArgs']]]]:
        """
        The components an automated incident impacts, with the impact each gets.
        """
        return pulumi.get(self, "components")

    @components.setter
    def components(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['StatusPageV3AutomationRuleComponentArgs']]]]):
        pulumi.set(self, "components", value)

    @_builtins.property
    @pulumi.getter(name="coolDownWindowMinutes")
    def cool_down_window_minutes(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Minimum minutes after an automated incident before this rule may open the next one. `0` disables the cool down. (Default `5`).
        """
        return pulumi.get(self, "cool_down_window_minutes")

    @cool_down_window_minutes.setter
    def cool_down_window_minutes(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "cool_down_window_minutes", value)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        A disabled rule never opens incidents. (Default `true`).
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "enabled", value)

    @_builtins.property
    @pulumi.getter(name="firstUpdate")
    def first_update(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Body of the status update that opens the incident.
        """
        return pulumi.get(self, "first_update")

    @first_update.setter
    def first_update(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "first_update", value)

    @_builtins.property
    @pulumi.getter(name="lastUpdate")
    def last_update(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Body of the status update that resolves the incident.
        """
        return pulumi.get(self, "last_update")

    @last_update.setter
    def last_update(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "last_update", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The name of the rule.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="notifySubscribers")
    def notify_subscribers(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether subscribers are notified of the automated updates. (Default `true`).
        """
        return pulumi.get(self, "notify_subscribers")

    @notify_subscribers.setter
    def notify_subscribers(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "notify_subscribers", value)

    @_builtins.property
    @pulumi.getter(name="statusPageId")
    def status_page_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The ID of the v3 status page the rule belongs to.
        """
        return pulumi.get(self, "status_page_id")

    @status_page_id.setter
    def status_page_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "status_page_id", value)

    @_builtins.property
    @pulumi.getter
    def tags(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        A failing check matches this rule when it, or its group, carries ANY of these tags. At least one tag is required.
        """
        return pulumi.get(self, "tags")

    @tags.setter
    def tags(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "tags", value)


@pulumi.type_token("checkly:index/statusPageV3AutomationRule:StatusPageV3AutomationRule")
class StatusPageV3AutomationRule(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 components: Optional[pulumi.Input[Sequence[pulumi.Input[Union['StatusPageV3AutomationRuleComponentArgs', 'StatusPageV3AutomationRuleComponentArgsDict']]]]] = None,
                 cool_down_window_minutes: Optional[pulumi.Input[_builtins.int]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 first_update: Optional[pulumi.Input[_builtins.str]] = None,
                 last_update: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 notify_subscribers: Optional[pulumi.Input[_builtins.bool]] = None,
                 status_page_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        An automation rule of a v3 status page. When a check whose tags overlap with the rule's tags fails, Checkly opens one incident on the page impacting the listed components, and resolves it when the check recovers. Import uses the composite ID `<status_page_id>/<rule_id>`.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_checkly as checkly

        example = checkly.StatusPageV3("example",
            name="Example Application",
            url="my-example-status-page")
        api = checkly.StatusPageV3Component("api",
            status_page_id=example.id,
            name="API",
            display_order=0)
        # When a check tagged "api" fails, an incident is opened on the page marking
        # the API component as a major outage, and resolved when the check recovers.
        api_outage = checkly.StatusPageV3AutomationRule("api_outage",
            status_page_id=example.id,
            name="API outage",
            first_update="We are investigating an issue with the API.",
            last_update="The issue has been resolved.",
            tags=["api"],
            components=[{
                "component_id": api.id,
                "target_impact": "MAJOR_OUTAGE",
            }])
        ```

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['StatusPageV3AutomationRuleComponentArgs', 'StatusPageV3AutomationRuleComponentArgsDict']]]] components: The components an automated incident impacts, with the impact each gets.
        :param pulumi.Input[_builtins.int] cool_down_window_minutes: Minimum minutes after an automated incident before this rule may open the next one. `0` disables the cool down. (Default `5`).
        :param pulumi.Input[_builtins.bool] enabled: A disabled rule never opens incidents. (Default `true`).
        :param pulumi.Input[_builtins.str] first_update: Body of the status update that opens the incident.
        :param pulumi.Input[_builtins.str] last_update: Body of the status update that resolves the incident.
        :param pulumi.Input[_builtins.str] name: The name of the rule.
        :param pulumi.Input[_builtins.bool] notify_subscribers: Whether subscribers are notified of the automated updates. (Default `true`).
        :param pulumi.Input[_builtins.str] status_page_id: The ID of the v3 status page the rule belongs to.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: A failing check matches this rule when it, or its group, carries ANY of these tags. At least one tag is required.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: StatusPageV3AutomationRuleArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        An automation rule of a v3 status page. When a check whose tags overlap with the rule's tags fails, Checkly opens one incident on the page impacting the listed components, and resolves it when the check recovers. Import uses the composite ID `<status_page_id>/<rule_id>`.

        ## Example Usage

        ```python
        import pulumi
        import pulumi_checkly as checkly

        example = checkly.StatusPageV3("example",
            name="Example Application",
            url="my-example-status-page")
        api = checkly.StatusPageV3Component("api",
            status_page_id=example.id,
            name="API",
            display_order=0)
        # When a check tagged "api" fails, an incident is opened on the page marking
        # the API component as a major outage, and resolved when the check recovers.
        api_outage = checkly.StatusPageV3AutomationRule("api_outage",
            status_page_id=example.id,
            name="API outage",
            first_update="We are investigating an issue with the API.",
            last_update="The issue has been resolved.",
            tags=["api"],
            components=[{
                "component_id": api.id,
                "target_impact": "MAJOR_OUTAGE",
            }])
        ```

        :param str resource_name: The name of the resource.
        :param StatusPageV3AutomationRuleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(StatusPageV3AutomationRuleArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 components: Optional[pulumi.Input[Sequence[pulumi.Input[Union['StatusPageV3AutomationRuleComponentArgs', 'StatusPageV3AutomationRuleComponentArgsDict']]]]] = None,
                 cool_down_window_minutes: Optional[pulumi.Input[_builtins.int]] = None,
                 enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 first_update: Optional[pulumi.Input[_builtins.str]] = None,
                 last_update: Optional[pulumi.Input[_builtins.str]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 notify_subscribers: Optional[pulumi.Input[_builtins.bool]] = None,
                 status_page_id: Optional[pulumi.Input[_builtins.str]] = None,
                 tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = StatusPageV3AutomationRuleArgs.__new__(StatusPageV3AutomationRuleArgs)

            __props__.__dict__["components"] = components
            __props__.__dict__["cool_down_window_minutes"] = cool_down_window_minutes
            __props__.__dict__["enabled"] = enabled
            if first_update is None and not opts.urn:
                raise TypeError("Missing required property 'first_update'")
            __props__.__dict__["first_update"] = first_update
            if last_update is None and not opts.urn:
                raise TypeError("Missing required property 'last_update'")
            __props__.__dict__["last_update"] = last_update
            __props__.__dict__["name"] = name
            __props__.__dict__["notify_subscribers"] = notify_subscribers
            if status_page_id is None and not opts.urn:
                raise TypeError("Missing required property 'status_page_id'")
            __props__.__dict__["status_page_id"] = status_page_id
            if tags is None and not opts.urn:
                raise TypeError("Missing required property 'tags'")
            __props__.__dict__["tags"] = tags
        super(StatusPageV3AutomationRule, __self__).__init__(
            'checkly:index/statusPageV3AutomationRule:StatusPageV3AutomationRule',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            components: Optional[pulumi.Input[Sequence[pulumi.Input[Union['StatusPageV3AutomationRuleComponentArgs', 'StatusPageV3AutomationRuleComponentArgsDict']]]]] = None,
            cool_down_window_minutes: Optional[pulumi.Input[_builtins.int]] = None,
            enabled: Optional[pulumi.Input[_builtins.bool]] = None,
            first_update: Optional[pulumi.Input[_builtins.str]] = None,
            last_update: Optional[pulumi.Input[_builtins.str]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            notify_subscribers: Optional[pulumi.Input[_builtins.bool]] = None,
            status_page_id: Optional[pulumi.Input[_builtins.str]] = None,
            tags: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None) -> 'StatusPageV3AutomationRule':
        """
        Get an existing StatusPageV3AutomationRule resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[Union['StatusPageV3AutomationRuleComponentArgs', 'StatusPageV3AutomationRuleComponentArgsDict']]]] components: The components an automated incident impacts, with the impact each gets.
        :param pulumi.Input[_builtins.int] cool_down_window_minutes: Minimum minutes after an automated incident before this rule may open the next one. `0` disables the cool down. (Default `5`).
        :param pulumi.Input[_builtins.bool] enabled: A disabled rule never opens incidents. (Default `true`).
        :param pulumi.Input[_builtins.str] first_update: Body of the status update that opens the incident.
        :param pulumi.Input[_builtins.str] last_update: Body of the status update that resolves the incident.
        :param pulumi.Input[_builtins.str] name: The name of the rule.
        :param pulumi.Input[_builtins.bool] notify_subscribers: Whether subscribers are notified of the automated updates. (Default `true`).
        :param pulumi.Input[_builtins.str] status_page_id: The ID of the v3 status page the rule belongs to.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] tags: A failing check matches this rule when it, or its group, carries ANY of these tags. At least one tag is required.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _StatusPageV3AutomationRuleState.__new__(_StatusPageV3AutomationRuleState)

        __props__.__dict__["components"] = components
        __props__.__dict__["cool_down_window_minutes"] = cool_down_window_minutes
        __props__.__dict__["enabled"] = enabled
        __props__.__dict__["first_update"] = first_update
        __props__.__dict__["last_update"] = last_update
        __props__.__dict__["name"] = name
        __props__.__dict__["notify_subscribers"] = notify_subscribers
        __props__.__dict__["status_page_id"] = status_page_id
        __props__.__dict__["tags"] = tags
        return StatusPageV3AutomationRule(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def components(self) -> pulumi.Output[Optional[Sequence['outputs.StatusPageV3AutomationRuleComponent']]]:
        """
        The components an automated incident impacts, with the impact each gets.
        """
        return pulumi.get(self, "components")

    @_builtins.property
    @pulumi.getter(name="coolDownWindowMinutes")
    def cool_down_window_minutes(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Minimum minutes after an automated incident before this rule may open the next one. `0` disables the cool down. (Default `5`).
        """
        return pulumi.get(self, "cool_down_window_minutes")

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        A disabled rule never opens incidents. (Default `true`).
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="firstUpdate")
    def first_update(self) -> pulumi.Output[_builtins.str]:
        """
        Body of the status update that opens the incident.
        """
        return pulumi.get(self, "first_update")

    @_builtins.property
    @pulumi.getter(name="lastUpdate")
    def last_update(self) -> pulumi.Output[_builtins.str]:
        """
        Body of the status update that resolves the incident.
        """
        return pulumi.get(self, "last_update")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The name of the rule.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="notifySubscribers")
    def notify_subscribers(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether subscribers are notified of the automated updates. (Default `true`).
        """
        return pulumi.get(self, "notify_subscribers")

    @_builtins.property
    @pulumi.getter(name="statusPageId")
    def status_page_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the v3 status page the rule belongs to.
        """
        return pulumi.get(self, "status_page_id")

    @_builtins.property
    @pulumi.getter
    def tags(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        A failing check matches this rule when it, or its group, carries ANY of these tags. At least one tag is required.
        """
        return pulumi.get(self, "tags")

