// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Checkly.Inputs
{

    public sealed class AlertChannelPagerdutyArgs : global::Pulumi.ResourceArgs
    {
        [Input("account")]
        public Input<string>? Account { get; set; }

        [Input("serviceKey", required: true)]
        public Input<string> ServiceKey { get; set; } = null!;

        [Input("serviceName")]
        public Input<string>? ServiceName { get; set; }

        public AlertChannelPagerdutyArgs()
        {
        }
        public static new AlertChannelPagerdutyArgs Empty => new AlertChannelPagerdutyArgs();
    }
}
