// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Checkly.Inputs
{

    public sealed class CheckAlertSettingsArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Determines what type of escalation to use. Possible values are `RUN_BASED` or `TIME_BASED`.
        /// </summary>
        [Input("escalationType")]
        public Input<string>? EscalationType { get; set; }

        [Input("reminders")]
        private InputList<Inputs.CheckAlertSettingsReminderArgs>? _reminders;

        /// <summary>
        /// . Possible arguments:
        /// </summary>
        public InputList<Inputs.CheckAlertSettingsReminderArgs> Reminders
        {
            get => _reminders ?? (_reminders = new InputList<Inputs.CheckAlertSettingsReminderArgs>());
            set => _reminders = value;
        }

        [Input("runBasedEscalations")]
        private InputList<Inputs.CheckAlertSettingsRunBasedEscalationArgs>? _runBasedEscalations;

        /// <summary>
        /// . Possible arguments:
        /// </summary>
        public InputList<Inputs.CheckAlertSettingsRunBasedEscalationArgs> RunBasedEscalations
        {
            get => _runBasedEscalations ?? (_runBasedEscalations = new InputList<Inputs.CheckAlertSettingsRunBasedEscalationArgs>());
            set => _runBasedEscalations = value;
        }

        [Input("sslCertificates")]
        private InputList<Inputs.CheckAlertSettingsSslCertificateArgs>? _sslCertificates;

        /// <summary>
        /// At what interval the reminders should be send.  Possible arguments:
        /// </summary>
        public InputList<Inputs.CheckAlertSettingsSslCertificateArgs> SslCertificates
        {
            get => _sslCertificates ?? (_sslCertificates = new InputList<Inputs.CheckAlertSettingsSslCertificateArgs>());
            set => _sslCertificates = value;
        }

        [Input("timeBasedEscalations")]
        private InputList<Inputs.CheckAlertSettingsTimeBasedEscalationArgs>? _timeBasedEscalations;

        /// <summary>
        /// . Possible arguments:
        /// </summary>
        public InputList<Inputs.CheckAlertSettingsTimeBasedEscalationArgs> TimeBasedEscalations
        {
            get => _timeBasedEscalations ?? (_timeBasedEscalations = new InputList<Inputs.CheckAlertSettingsTimeBasedEscalationArgs>());
            set => _timeBasedEscalations = value;
        }

        public CheckAlertSettingsArgs()
        {
        }
    }
}
