// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Checkly.Inputs
{

    public sealed class CheckGroupV2DefaultRuntimeGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The runtime ID.
        /// </summary>
        [Input("runtimeId", required: true)]
        public Input<string> RuntimeId { get; set; } = null!;

        public CheckGroupV2DefaultRuntimeGetArgs()
        {
        }
        public static new CheckGroupV2DefaultRuntimeGetArgs Empty => new CheckGroupV2DefaultRuntimeGetArgs();
    }
}
