// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Checkly.Inputs
{

    public sealed class CheckGroupV2TeardownScriptArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A valid piece of Node.js code.
        /// </summary>
        [Input("inlineScript")]
        public Input<string>? InlineScript { get; set; }

        /// <summary>
        /// The ID of a code snippet. Code snippets are not available for new plans.
        /// </summary>
        [Input("snippetId")]
        public Input<int>? SnippetId { get; set; }

        public CheckGroupV2TeardownScriptArgs()
        {
        }
        public static new CheckGroupV2TeardownScriptArgs Empty => new CheckGroupV2TeardownScriptArgs();
    }
}
