// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Checkly.Inputs
{

    public sealed class GrpcMonitorRequestMetadataArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The gRPC metadata (header) key.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// The gRPC metadata (header) value.
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public GrpcMonitorRequestMetadataArgs()
        {
        }
        public static new GrpcMonitorRequestMetadataArgs Empty => new GrpcMonitorRequestMetadataArgs();
    }
}
