// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Checkly.Inputs
{

    public sealed class HeartbeatMonitorAlertSettingsReminderGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Number of reminder notifications to send. Possible values are `0`, `1`, `2`, `3`, `4`, `5`, and `100000` (`0` to disable, `100000` for unlimited). (Default `0`).
        /// </summary>
        [Input("amount")]
        public Input<int>? Amount { get; set; }

        /// <summary>
        /// Interval between reminder notifications in minutes. Possible values are `5`, `10`, `15`, and `30`. (Default `5`).
        /// </summary>
        [Input("interval")]
        public Input<int>? Interval { get; set; }

        public HeartbeatMonitorAlertSettingsReminderGetArgs()
        {
        }
        public static new HeartbeatMonitorAlertSettingsReminderGetArgs Empty => new HeartbeatMonitorAlertSettingsReminderGetArgs();
    }
}
