// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Checkly.Inputs
{

    public sealed class PlaywrightCheckSuiteRuntimePlaywrightGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("devices")]
        private InputList<Inputs.PlaywrightCheckSuiteRuntimePlaywrightDeviceGetArgs>? _devices;

        /// <summary>
        /// The list of devices that should be made available for Playwright. Defaults to chromium, firefox, and webkit.
        /// </summary>
        public InputList<Inputs.PlaywrightCheckSuiteRuntimePlaywrightDeviceGetArgs> Devices
        {
            get => _devices ?? (_devices = new InputList<Inputs.PlaywrightCheckSuiteRuntimePlaywrightDeviceGetArgs>());
            set => _devices = value;
        }

        /// <summary>
        /// The Playwright version to use. Defaults to the version detected from the code bundle's lockfile.
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public PlaywrightCheckSuiteRuntimePlaywrightGetArgs()
        {
        }
        public static new PlaywrightCheckSuiteRuntimePlaywrightGetArgs Empty => new PlaywrightCheckSuiteRuntimePlaywrightGetArgs();
    }
}
