// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Checkly.Inputs
{

    public sealed class SslMonitorRequestSecurityBaselineMinTlsVersionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// What happens when the rule is violated: `fail` fails the monitor, `degrade` marks it degraded, `ignore` disables the rule. (Default `fail`).
        /// </summary>
        [Input("severity")]
        public Input<string>? Severity { get; set; }

        /// <summary>
        /// The TLS version. Possible values are `TLS1.2` and `TLS1.3`. (Default `TLS1.2`).
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public SslMonitorRequestSecurityBaselineMinTlsVersionArgs()
        {
        }
        public static new SslMonitorRequestSecurityBaselineMinTlsVersionArgs Empty => new SslMonitorRequestSecurityBaselineMinTlsVersionArgs();
    }
}
