// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Checkly.Inputs
{

    public sealed class SslMonitorRetryStrategyOnlyOnArgs : global::Pulumi.ResourceArgs
    {
        public SslMonitorRetryStrategyOnlyOnArgs()
        {
        }
        public static new SslMonitorRetryStrategyOnlyOnArgs Empty => new SslMonitorRetryStrategyOnlyOnArgs();
    }
}
