// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Checkly.Inputs
{

    public sealed class TcpCheckAlertSettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Determines the type of escalation to use. Possible values are `RUN_BASED` and `TIME_BASED`. (Default `RUN_BASED`).
        /// </summary>
        [Input("escalationType")]
        public Input<string>? EscalationType { get; set; }

        [Input("parallelRunFailureThresholds")]
        private InputList<Inputs.TcpCheckAlertSettingsParallelRunFailureThresholdArgs>? _parallelRunFailureThresholds;

        /// <summary>
        /// Configuration for parallel run failure threshold.
        /// </summary>
        public InputList<Inputs.TcpCheckAlertSettingsParallelRunFailureThresholdArgs> ParallelRunFailureThresholds
        {
            get => _parallelRunFailureThresholds ?? (_parallelRunFailureThresholds = new InputList<Inputs.TcpCheckAlertSettingsParallelRunFailureThresholdArgs>());
            set => _parallelRunFailureThresholds = value;
        }

        [Input("reminders")]
        private InputList<Inputs.TcpCheckAlertSettingsReminderArgs>? _reminders;

        /// <summary>
        /// Defines how often to send reminder notifications after initial alert.
        /// </summary>
        public InputList<Inputs.TcpCheckAlertSettingsReminderArgs> Reminders
        {
            get => _reminders ?? (_reminders = new InputList<Inputs.TcpCheckAlertSettingsReminderArgs>());
            set => _reminders = value;
        }

        [Input("runBasedEscalations")]
        private InputList<Inputs.TcpCheckAlertSettingsRunBasedEscalationArgs>? _runBasedEscalations;

        /// <summary>
        /// Configuration for run-based escalation.
        /// </summary>
        public InputList<Inputs.TcpCheckAlertSettingsRunBasedEscalationArgs> RunBasedEscalations
        {
            get => _runBasedEscalations ?? (_runBasedEscalations = new InputList<Inputs.TcpCheckAlertSettingsRunBasedEscalationArgs>());
            set => _runBasedEscalations = value;
        }

        [Input("timeBasedEscalations")]
        private InputList<Inputs.TcpCheckAlertSettingsTimeBasedEscalationArgs>? _timeBasedEscalations;

        /// <summary>
        /// Configuration for time-based escalation.
        /// </summary>
        public InputList<Inputs.TcpCheckAlertSettingsTimeBasedEscalationArgs> TimeBasedEscalations
        {
            get => _timeBasedEscalations ?? (_timeBasedEscalations = new InputList<Inputs.TcpCheckAlertSettingsTimeBasedEscalationArgs>());
            set => _timeBasedEscalations = value;
        }

        public TcpCheckAlertSettingsArgs()
        {
        }
        public static new TcpCheckAlertSettingsArgs Empty => new TcpCheckAlertSettingsArgs();
    }
}
