// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Checkly.Inputs
{

    public sealed class TcpCheckAlertSettingsParallelRunFailureThresholdGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Applicable only for checks scheduled in parallel in multiple locations.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Possible values are `10`, `20`, `30`, `40`, `50`, `60`, `70`, `80`, `100`, and `100`. (Default `10`).
        /// </summary>
        [Input("percentage")]
        public Input<int>? Percentage { get; set; }

        public TcpCheckAlertSettingsParallelRunFailureThresholdGetArgs()
        {
        }
        public static new TcpCheckAlertSettingsParallelRunFailureThresholdGetArgs Empty => new TcpCheckAlertSettingsParallelRunFailureThresholdGetArgs();
    }
}
