// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Checkly.Inputs
{

    public sealed class UrlMonitorAlertChannelSubscriptionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether an alert should be sent to this channel.
        /// </summary>
        [Input("activated", required: true)]
        public Input<bool> Activated { get; set; } = null!;

        /// <summary>
        /// The ID of the alert channel.
        /// </summary>
        [Input("channelId", required: true)]
        public Input<int> ChannelId { get; set; } = null!;

        public UrlMonitorAlertChannelSubscriptionArgs()
        {
        }
        public static new UrlMonitorAlertChannelSubscriptionArgs Empty => new UrlMonitorAlertChannelSubscriptionArgs();
    }
}
