name: Release 🚀
on:
  push:
    tags:
      - 'v*'

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  PUBLISH_NPM: true
  NPM_REGISTRY_URL: https://registry.npmjs.org

jobs:
  publish-binary:
    name: Publish Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow to restore tags
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16.x

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          always-auth: true

      - name: Install pulumictl
        run: curl -L https://github.com/pulumi/pulumictl/releases/download/v0.0.25/pulumictl-v0.0.25-linux-amd64.tar.gz | sudo tar zxv -C /usr/bin -f- pulumictl

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist

  publish-sdk:
    name: Publish SDKs
    runs-on: ubuntu-latest
    needs: publish-binary
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Unshallow clone for tag3
        run: git fetch --prune --unshallow --tags
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.goversion }}
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with:
          repo: pulumi/pulumictl
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v2.0.0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.nodeversion }}
          registry-url: ${{ env.NPM_REGISTRY_URL }}
      - name: Build SDK
        run: make build_${{ matrix.language }}_sdk
      - name: Check worktree clean
        run: |
          git update-index -q --refresh
          if ! git diff-files --quiet; then
              >&2 echo "error: working tree is not clean, aborting!"
              git status
              git diff
              exit 1
          fi
      - if: ${{ matrix.language == 'nodejs' && env.PUBLISH_NPM == 'true' }}
        uses: JS-DevTools/npm-publish@v1
        with:
          access: "public"
          token: ${{ env.NPM_TOKEN }}
          package: ${{ github.workspace }}/sdk/nodejs/bin/package.json
    strategy:
      fail-fast: true
      matrix:
        dotnetversion:
          - 3.1.301
        goversion:
          - 1.17.x
        language:
          - nodejs
        nodeversion:
          - 14.x
        pythonversion:
          - "3.9"