// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Check groups organize related checks together and allow optional shared configuration.
 *
 * Unlike `checkly.CheckGroup` (v1), which always imposed implicit defaults for various settings, `checkly.CheckGroupV2` does not override any check settings by default. A group can be as minimal as just a name. Use the optional `enforce_*` blocks only when you explicitly want the group to override individual check settings.
 *
 * The new `checkly.CheckGroupV2` resource should always be preferred over the old `checkly.CheckGroup` resource.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as checkly from "@checkly/pulumi";
 *
 * // Minimal example: just a folder to organize checks.
 * const just_a_folder = new checkly.CheckGroupV2("just-a-folder", {name: "Just a Folder"});
 * // Full example: a group with enforced settings that override individual checks.
 * const production_api = new checkly.CheckGroupV2("production-api", {
 *     name: "Production API",
 *     activated: true,
 *     muted: false,
 *     concurrency: 5,
 *     tags: [
 *         "production",
 *         "api",
 *     ],
 *     enforceLocations: {
 *         enabled: true,
 *         locations: [
 *             "us-east-1",
 *             "eu-west-1",
 *             "ap-southeast-1",
 *         ],
 *         privateLocations: ["my-datacenter"],
 *     },
 *     enforceRetryStrategy: {
 *         enabled: true,
 *         retryStrategy: {
 *             type: "LINEAR",
 *             baseBackoffSeconds: 30,
 *             maxRetries: 3,
 *             maxDurationSeconds: 300,
 *             sameRegion: true,
 *         },
 *     },
 *     enforceSchedulingStrategy: {
 *         enabled: true,
 *         runParallel: true,
 *     },
 *     enforceAlertSettings: {
 *         enabled: true,
 *         alertSettings: {
 *             escalationType: "RUN_BASED",
 *             runBasedEscalations: [{
 *                 failedRunThreshold: 2,
 *             }],
 *             reminders: [{
 *                 amount: 3,
 *                 interval: 10,
 *             }],
 *             parallelRunFailureThresholds: [{
 *                 enabled: true,
 *                 percentage: 50,
 *             }],
 *         },
 *         alertChannelSubscriptions: [{
 *             channelId: 1234,
 *             activated: true,
 *         }],
 *     },
 *     environmentVariables: [
 *         {
 *             key: "BASE_URL",
 *             value: "https://api.example.com",
 *             locked: false,
 *         },
 *         {
 *             key: "API_TOKEN",
 *             value: "super-secret-token",
 *             locked: true,
 *             secret: true,
 *         },
 *     ],
 *     defaultRuntime: {
 *         runtimeId: "2024.02",
 *     },
 *     apiCheckDefaults: {
 *         url: "https://api.example.com/",
 *         headers: {
 *             "X-Api-Key": "{{API_TOKEN}}",
 *             "Content-Type": "application/json",
 *         },
 *         queryParameters: {
 *             version: "v2",
 *         },
 *         assertions: [
 *             {
 *                 source: "STATUS_CODE",
 *                 comparison: "LESS_THAN",
 *                 target: "400",
 *             },
 *             {
 *                 source: "RESPONSE_TIME",
 *                 comparison: "LESS_THAN",
 *                 target: "3000",
 *             },
 *         ],
 *         basicAuth: {
 *             username: "admin",
 *             password: "pass",
 *         },
 *     },
 *     setupScript: {
 *         inlineScript: `// Runs before every API check in this group
 * console.log("Setting up...")
 * `,
 *     },
 *     teardownScript: {
 *         inlineScript: `// Runs after every API check in this group
 * console.log("Tearing down...")
 * `,
 *     },
 * });
 * // Example: enforce only retry strategy with network-error-only retries.
 * const retry_on_network_errors = new checkly.CheckGroupV2("retry-on-network-errors", {
 *     name: "Retry on Network Errors Only",
 *     enforceRetryStrategy: {
 *         enabled: true,
 *         retryStrategy: {
 *             type: "EXPONENTIAL",
 *             baseBackoffSeconds: 10,
 *             maxRetries: 5,
 *             maxDurationSeconds: 600,
 *             sameRegion: false,
 *             onlyOn: {
 *                 networkError: true,
 *             },
 *         },
 *     },
 * });
 * // Example: enforce time-based alert escalation.
 * const time_based_alerts = new checkly.CheckGroupV2("time-based-alerts", {
 *     name: "Time-Based Alert Escalation",
 *     enforceAlertSettings: {
 *         enabled: true,
 *         alertSettings: {
 *             escalationType: "TIME_BASED",
 *             timeBasedEscalations: [{
 *                 minutesFailingThreshold: 10,
 *             }],
 *             reminders: [{
 *                 amount: 5,
 *                 interval: 15,
 *             }],
 *         },
 *     },
 * });
 * // Example: use global alert settings instead of custom ones.
 * const use_global_alerts = new checkly.CheckGroupV2("use-global-alerts", {
 *     name: "Use Global Alert Settings",
 *     enforceAlertSettings: {
 *         enabled: true,
 *         useGlobalAlertSettings: true,
 *     },
 * });
 * // Example: enforce alert channel subscriptions with custom alert settings.
 * const email = new checkly.AlertChannel("email", {email: {
 *     address: "alerts@example.com",
 * }});
 * const slack = new checkly.AlertChannel("slack", {slack: {
 *     channel: "#alerts",
 *     url: "https://hooks.slack.com/services/TXXXXX/XXXXX/XXXXXXXXXX",
 * }});
 * const with_alert_channels = new checkly.CheckGroupV2("with-alert-channels", {
 *     name: "Group with Alert Channels",
 *     enforceAlertSettings: {
 *         enabled: true,
 *         alertSettings: {
 *             escalationType: "RUN_BASED",
 *             runBasedEscalations: [{
 *                 failedRunThreshold: 1,
 *             }],
 *             reminders: [{
 *                 amount: 0,
 *                 interval: 5,
 *             }],
 *         },
 *         alertChannelSubscriptions: [
 *             {
 *                 channelId: email.id,
 *                 activated: true,
 *             },
 *             {
 *                 channelId: slack.id,
 *                 activated: true,
 *             },
 *         ],
 *     },
 * });
 * // Example: enforce no retries.
 * const no_retries = new checkly.CheckGroupV2("no-retries", {
 *     name: "No Retries Group",
 *     enforceRetryStrategy: {
 *         enabled: true,
 *         retryStrategy: {
 *             type: "NO_RETRIES",
 *         },
 *     },
 * });
 * // Example: enforce a single retry.
 * const single_retry = new checkly.CheckGroupV2("single-retry", {
 *     name: "Single Retry Group",
 *     enforceRetryStrategy: {
 *         enabled: true,
 *         retryStrategy: {
 *             type: "SINGLE_RETRY",
 *             baseBackoffSeconds: 10,
 *             sameRegion: true,
 *         },
 *     },
 * });
 * ```
 */
export class CheckGroupV2 extends pulumi.CustomResource {
    /**
     * Get an existing CheckGroupV2 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CheckGroupV2State, opts?: pulumi.CustomResourceOptions): CheckGroupV2 {
        return new CheckGroupV2(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'checkly:index/checkGroupV2:CheckGroupV2';

    /**
     * Returns true if the given object is an instance of CheckGroupV2.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CheckGroupV2 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CheckGroupV2.__pulumiType;
    }

    /**
     * Determines whether activated checks in the group should run or not. Deactivating the group will prevent all checks in the group from running, regardless of their activated state. (Default `true`).
     */
    declare public readonly activated: pulumi.Output<boolean | undefined>;
    declare public readonly apiCheckDefaults: pulumi.Output<outputs.CheckGroupV2ApiCheckDefaults>;
    /**
     * Determines the number of checks to run concurrently when triggering the check group via CI/CD or the API. (Default `1`).
     */
    declare public readonly concurrency: pulumi.Output<number | undefined>;
    /**
     * Sets a default runtime for the group. Used as a fallback when a check belonging to the group has no runtime set. Takes precedence over the account default runtime.
     */
    declare public readonly defaultRuntime: pulumi.Output<outputs.CheckGroupV2DefaultRuntime | undefined>;
    /**
     * Enforces alert settings for the whole group. Overrides check configuration.
     */
    declare public readonly enforceAlertSettings: pulumi.Output<outputs.CheckGroupV2EnforceAlertSettings>;
    /**
     * Enforces public and private locations for the whole group. Overrides check configuration.
     */
    declare public readonly enforceLocations: pulumi.Output<outputs.CheckGroupV2EnforceLocations>;
    /**
     * Enforces a retry strategy for the whole group. Overrides check configuration.
     */
    declare public readonly enforceRetryStrategy: pulumi.Output<outputs.CheckGroupV2EnforceRetryStrategy>;
    /**
     * Enforces a scheduling strategy for the whole group. Overrides check configuration.
     */
    declare public readonly enforceSchedulingStrategy: pulumi.Output<outputs.CheckGroupV2EnforceSchedulingStrategy>;
    /**
     * Insert environment variables into the runtime environment of checks in the group. Only relevant for check types that support environment variables. Use global environment variables whenever possible.
     */
    declare public readonly environmentVariables: pulumi.Output<outputs.CheckGroupV2EnvironmentVariable[] | undefined>;
    /**
     * Determines if any notifications will be sent out when a check in this group fails and/or recovers. Muting the group will deactivate all notifications for all checks in the group, regardless of their muted state. (Default `false`).
     */
    declare public readonly muted: pulumi.Output<boolean | undefined>;
    /**
     * The name of the check group.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * A script to run in the setup phase of an API check. Runs in addition to the check's own setup script.
     */
    declare public readonly setupScript: pulumi.Output<outputs.CheckGroupV2SetupScript | undefined>;
    /**
     * Additional tags to append to all checks in the group.
     */
    declare public readonly tags: pulumi.Output<string[] | undefined>;
    /**
     * A script to run in the teardown phase of an API check. Runs in addition to the check's own teardown script.
     */
    declare public readonly teardownScript: pulumi.Output<outputs.CheckGroupV2TeardownScript | undefined>;

    /**
     * Create a CheckGroupV2 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: CheckGroupV2Args, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CheckGroupV2Args | CheckGroupV2State, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CheckGroupV2State | undefined;
            resourceInputs["activated"] = state?.activated;
            resourceInputs["apiCheckDefaults"] = state?.apiCheckDefaults;
            resourceInputs["concurrency"] = state?.concurrency;
            resourceInputs["defaultRuntime"] = state?.defaultRuntime;
            resourceInputs["enforceAlertSettings"] = state?.enforceAlertSettings;
            resourceInputs["enforceLocations"] = state?.enforceLocations;
            resourceInputs["enforceRetryStrategy"] = state?.enforceRetryStrategy;
            resourceInputs["enforceSchedulingStrategy"] = state?.enforceSchedulingStrategy;
            resourceInputs["environmentVariables"] = state?.environmentVariables;
            resourceInputs["muted"] = state?.muted;
            resourceInputs["name"] = state?.name;
            resourceInputs["setupScript"] = state?.setupScript;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["teardownScript"] = state?.teardownScript;
        } else {
            const args = argsOrState as CheckGroupV2Args | undefined;
            resourceInputs["activated"] = args?.activated;
            resourceInputs["apiCheckDefaults"] = args ? (args.apiCheckDefaults ? pulumi.output(args.apiCheckDefaults).apply(inputs.checkGroupV2ApiCheckDefaultsProvideDefaults) : undefined) : undefined;
            resourceInputs["concurrency"] = args?.concurrency;
            resourceInputs["defaultRuntime"] = args?.defaultRuntime;
            resourceInputs["enforceAlertSettings"] = args?.enforceAlertSettings;
            resourceInputs["enforceLocations"] = args?.enforceLocations;
            resourceInputs["enforceRetryStrategy"] = args?.enforceRetryStrategy;
            resourceInputs["enforceSchedulingStrategy"] = args?.enforceSchedulingStrategy;
            resourceInputs["environmentVariables"] = args?.environmentVariables;
            resourceInputs["muted"] = args?.muted;
            resourceInputs["name"] = args?.name;
            resourceInputs["setupScript"] = args?.setupScript;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["teardownScript"] = args?.teardownScript;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CheckGroupV2.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CheckGroupV2 resources.
 */
export interface CheckGroupV2State {
    /**
     * Determines whether activated checks in the group should run or not. Deactivating the group will prevent all checks in the group from running, regardless of their activated state. (Default `true`).
     */
    activated?: pulumi.Input<boolean>;
    apiCheckDefaults?: pulumi.Input<inputs.CheckGroupV2ApiCheckDefaults>;
    /**
     * Determines the number of checks to run concurrently when triggering the check group via CI/CD or the API. (Default `1`).
     */
    concurrency?: pulumi.Input<number>;
    /**
     * Sets a default runtime for the group. Used as a fallback when a check belonging to the group has no runtime set. Takes precedence over the account default runtime.
     */
    defaultRuntime?: pulumi.Input<inputs.CheckGroupV2DefaultRuntime>;
    /**
     * Enforces alert settings for the whole group. Overrides check configuration.
     */
    enforceAlertSettings?: pulumi.Input<inputs.CheckGroupV2EnforceAlertSettings>;
    /**
     * Enforces public and private locations for the whole group. Overrides check configuration.
     */
    enforceLocations?: pulumi.Input<inputs.CheckGroupV2EnforceLocations>;
    /**
     * Enforces a retry strategy for the whole group. Overrides check configuration.
     */
    enforceRetryStrategy?: pulumi.Input<inputs.CheckGroupV2EnforceRetryStrategy>;
    /**
     * Enforces a scheduling strategy for the whole group. Overrides check configuration.
     */
    enforceSchedulingStrategy?: pulumi.Input<inputs.CheckGroupV2EnforceSchedulingStrategy>;
    /**
     * Insert environment variables into the runtime environment of checks in the group. Only relevant for check types that support environment variables. Use global environment variables whenever possible.
     */
    environmentVariables?: pulumi.Input<pulumi.Input<inputs.CheckGroupV2EnvironmentVariable>[]>;
    /**
     * Determines if any notifications will be sent out when a check in this group fails and/or recovers. Muting the group will deactivate all notifications for all checks in the group, regardless of their muted state. (Default `false`).
     */
    muted?: pulumi.Input<boolean>;
    /**
     * The name of the check group.
     */
    name?: pulumi.Input<string>;
    /**
     * A script to run in the setup phase of an API check. Runs in addition to the check's own setup script.
     */
    setupScript?: pulumi.Input<inputs.CheckGroupV2SetupScript>;
    /**
     * Additional tags to append to all checks in the group.
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A script to run in the teardown phase of an API check. Runs in addition to the check's own teardown script.
     */
    teardownScript?: pulumi.Input<inputs.CheckGroupV2TeardownScript>;
}

/**
 * The set of arguments for constructing a CheckGroupV2 resource.
 */
export interface CheckGroupV2Args {
    /**
     * Determines whether activated checks in the group should run or not. Deactivating the group will prevent all checks in the group from running, regardless of their activated state. (Default `true`).
     */
    activated?: pulumi.Input<boolean>;
    apiCheckDefaults?: pulumi.Input<inputs.CheckGroupV2ApiCheckDefaults>;
    /**
     * Determines the number of checks to run concurrently when triggering the check group via CI/CD or the API. (Default `1`).
     */
    concurrency?: pulumi.Input<number>;
    /**
     * Sets a default runtime for the group. Used as a fallback when a check belonging to the group has no runtime set. Takes precedence over the account default runtime.
     */
    defaultRuntime?: pulumi.Input<inputs.CheckGroupV2DefaultRuntime>;
    /**
     * Enforces alert settings for the whole group. Overrides check configuration.
     */
    enforceAlertSettings?: pulumi.Input<inputs.CheckGroupV2EnforceAlertSettings>;
    /**
     * Enforces public and private locations for the whole group. Overrides check configuration.
     */
    enforceLocations?: pulumi.Input<inputs.CheckGroupV2EnforceLocations>;
    /**
     * Enforces a retry strategy for the whole group. Overrides check configuration.
     */
    enforceRetryStrategy?: pulumi.Input<inputs.CheckGroupV2EnforceRetryStrategy>;
    /**
     * Enforces a scheduling strategy for the whole group. Overrides check configuration.
     */
    enforceSchedulingStrategy?: pulumi.Input<inputs.CheckGroupV2EnforceSchedulingStrategy>;
    /**
     * Insert environment variables into the runtime environment of checks in the group. Only relevant for check types that support environment variables. Use global environment variables whenever possible.
     */
    environmentVariables?: pulumi.Input<pulumi.Input<inputs.CheckGroupV2EnvironmentVariable>[]>;
    /**
     * Determines if any notifications will be sent out when a check in this group fails and/or recovers. Muting the group will deactivate all notifications for all checks in the group, regardless of their muted state. (Default `false`).
     */
    muted?: pulumi.Input<boolean>;
    /**
     * The name of the check group.
     */
    name?: pulumi.Input<string>;
    /**
     * A script to run in the setup phase of an API check. Runs in addition to the check's own setup script.
     */
    setupScript?: pulumi.Input<inputs.CheckGroupV2SetupScript>;
    /**
     * Additional tags to append to all checks in the group.
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A script to run in the teardown phase of an API check. Runs in addition to the check's own teardown script.
     */
    teardownScript?: pulumi.Input<inputs.CheckGroupV2TeardownScript>;
}
