// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Creates a DNS Monitor to check DNS record availability and response times.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as checkly from "@checkly/pulumi";
 *
 * const example_dns_monitor = new checkly.DnsMonitor("example-dns-monitor", {
 *     name: "Example DNS monitor",
 *     activated: true,
 *     frequency: 2,
 *     useGlobalAlertSettings: true,
 *     locations: ["eu-west-1"],
 *     request: {
 *         recordType: "A",
 *         query: "welcome.checklyhq.com",
 *         nameServer: {
 *             host: "1.1.1.1",
 *             port: 53,
 *         },
 *         assertions: [{
 *             source: "RESPONSE_CODE",
 *             comparison: "EQUALS",
 *             target: "NOERROR",
 *         }],
 *     },
 * });
 * ```
 */
export class DnsMonitor extends pulumi.CustomResource {
    /**
     * Get an existing DnsMonitor resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DnsMonitorState, opts?: pulumi.CustomResourceOptions): DnsMonitor {
        return new DnsMonitor(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'checkly:index/dnsMonitor:DnsMonitor';

    /**
     * Returns true if the given object is an instance of DnsMonitor.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DnsMonitor {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DnsMonitor.__pulumiType;
    }

    /**
     * Determines whether the monitor will run periodically or not after being deployed.
     */
    declare public readonly activated: pulumi.Output<boolean>;
    /**
     * An array of channel IDs and whether they're activated or not. If you don't set at least one alert subscription for your monitor, we won't be able to alert you.
     */
    declare public readonly alertChannelSubscriptions: pulumi.Output<outputs.DnsMonitorAlertChannelSubscription[] | undefined>;
    /**
     * Determines the alert escalation policy for the monitor.
     */
    declare public readonly alertSettings: pulumi.Output<outputs.DnsMonitorAlertSettings>;
    /**
     * The response time in milliseconds where the monitor should be considered degraded. Possible values are between `0` and `5000`. (Default `500`).
     */
    declare public readonly degradedResponseTime: pulumi.Output<number | undefined>;
    /**
     * How often the monitor should run in minutes. Possible values are `0`, `1`, `2`, `5`, `10`, `15`, `30`, `60`, `120`, `180`, `360`, `720`, and `1440`.
     */
    declare public readonly frequency: pulumi.Output<number>;
    /**
     * To create a high frequency monitor, set `frequency` to `0` and `frequencyOffset` to `10`, `20`, or `30`.
     */
    declare public readonly frequencyOffset: pulumi.Output<number | undefined>;
    /**
     * The ID of the check group that this monitor is part of.
     */
    declare public readonly groupId: pulumi.Output<number | undefined>;
    /**
     * The position of the monitor in the check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
     */
    declare public readonly groupOrder: pulumi.Output<number | undefined>;
    /**
     * An array of one or more data center locations where to run the this monitor.
     */
    declare public readonly locations: pulumi.Output<string[] | undefined>;
    /**
     * The response time in milliseconds where the monitor should be considered failing. Possible values are between `0` and `5000`. (Default `1000`).
     */
    declare public readonly maxResponseTime: pulumi.Output<number | undefined>;
    /**
     * Determines if any notifications will be sent out when the monitor fails and/or recovers. (Default `false`).
     */
    declare public readonly muted: pulumi.Output<boolean | undefined>;
    /**
     * The name of the monitor.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The parameters of the HTTP request.
     */
    declare public readonly request: pulumi.Output<outputs.DnsMonitorRequest>;
    /**
     * A strategy for retrying failed check/monitor runs.
     */
    declare public readonly retryStrategy: pulumi.Output<outputs.DnsMonitorRetryStrategy>;
    /**
     * Determines whether the monitor should run on all selected locations in parallel or round-robin. (Default `false`).
     */
    declare public readonly runParallel: pulumi.Output<boolean | undefined>;
    /**
     * A list of tags for organizing and filtering checks and monitors.
     */
    declare public readonly tags: pulumi.Output<string[] | undefined>;
    /**
     * Create and resolve an incident based on the alert configuration. Useful for status page automation.
     */
    declare public readonly triggerIncident: pulumi.Output<outputs.DnsMonitorTriggerIncident | undefined>;
    /**
     * When true, the account level alert settings will be used, not the alert setting defined on this monitor. (Default `true`).
     */
    declare public readonly useGlobalAlertSettings: pulumi.Output<boolean | undefined>;

    /**
     * Create a DnsMonitor resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DnsMonitorArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DnsMonitorArgs | DnsMonitorState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DnsMonitorState | undefined;
            resourceInputs["activated"] = state?.activated;
            resourceInputs["alertChannelSubscriptions"] = state?.alertChannelSubscriptions;
            resourceInputs["alertSettings"] = state?.alertSettings;
            resourceInputs["degradedResponseTime"] = state?.degradedResponseTime;
            resourceInputs["frequency"] = state?.frequency;
            resourceInputs["frequencyOffset"] = state?.frequencyOffset;
            resourceInputs["groupId"] = state?.groupId;
            resourceInputs["groupOrder"] = state?.groupOrder;
            resourceInputs["locations"] = state?.locations;
            resourceInputs["maxResponseTime"] = state?.maxResponseTime;
            resourceInputs["muted"] = state?.muted;
            resourceInputs["name"] = state?.name;
            resourceInputs["request"] = state?.request;
            resourceInputs["retryStrategy"] = state?.retryStrategy;
            resourceInputs["runParallel"] = state?.runParallel;
            resourceInputs["tags"] = state?.tags;
            resourceInputs["triggerIncident"] = state?.triggerIncident;
            resourceInputs["useGlobalAlertSettings"] = state?.useGlobalAlertSettings;
        } else {
            const args = argsOrState as DnsMonitorArgs | undefined;
            if (args?.activated === undefined && !opts.urn) {
                throw new Error("Missing required property 'activated'");
            }
            if (args?.frequency === undefined && !opts.urn) {
                throw new Error("Missing required property 'frequency'");
            }
            if (args?.request === undefined && !opts.urn) {
                throw new Error("Missing required property 'request'");
            }
            resourceInputs["activated"] = args?.activated;
            resourceInputs["alertChannelSubscriptions"] = args?.alertChannelSubscriptions;
            resourceInputs["alertSettings"] = args?.alertSettings;
            resourceInputs["degradedResponseTime"] = args?.degradedResponseTime;
            resourceInputs["frequency"] = args?.frequency;
            resourceInputs["frequencyOffset"] = args?.frequencyOffset;
            resourceInputs["groupId"] = args?.groupId;
            resourceInputs["groupOrder"] = args?.groupOrder;
            resourceInputs["locations"] = args?.locations;
            resourceInputs["maxResponseTime"] = args?.maxResponseTime;
            resourceInputs["muted"] = args?.muted;
            resourceInputs["name"] = args?.name;
            resourceInputs["request"] = args?.request;
            resourceInputs["retryStrategy"] = args?.retryStrategy;
            resourceInputs["runParallel"] = args?.runParallel;
            resourceInputs["tags"] = args?.tags;
            resourceInputs["triggerIncident"] = args?.triggerIncident;
            resourceInputs["useGlobalAlertSettings"] = args?.useGlobalAlertSettings;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DnsMonitor.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DnsMonitor resources.
 */
export interface DnsMonitorState {
    /**
     * Determines whether the monitor will run periodically or not after being deployed.
     */
    activated?: pulumi.Input<boolean>;
    /**
     * An array of channel IDs and whether they're activated or not. If you don't set at least one alert subscription for your monitor, we won't be able to alert you.
     */
    alertChannelSubscriptions?: pulumi.Input<pulumi.Input<inputs.DnsMonitorAlertChannelSubscription>[]>;
    /**
     * Determines the alert escalation policy for the monitor.
     */
    alertSettings?: pulumi.Input<inputs.DnsMonitorAlertSettings>;
    /**
     * The response time in milliseconds where the monitor should be considered degraded. Possible values are between `0` and `5000`. (Default `500`).
     */
    degradedResponseTime?: pulumi.Input<number>;
    /**
     * How often the monitor should run in minutes. Possible values are `0`, `1`, `2`, `5`, `10`, `15`, `30`, `60`, `120`, `180`, `360`, `720`, and `1440`.
     */
    frequency?: pulumi.Input<number>;
    /**
     * To create a high frequency monitor, set `frequency` to `0` and `frequencyOffset` to `10`, `20`, or `30`.
     */
    frequencyOffset?: pulumi.Input<number>;
    /**
     * The ID of the check group that this monitor is part of.
     */
    groupId?: pulumi.Input<number>;
    /**
     * The position of the monitor in the check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
     */
    groupOrder?: pulumi.Input<number>;
    /**
     * An array of one or more data center locations where to run the this monitor.
     */
    locations?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The response time in milliseconds where the monitor should be considered failing. Possible values are between `0` and `5000`. (Default `1000`).
     */
    maxResponseTime?: pulumi.Input<number>;
    /**
     * Determines if any notifications will be sent out when the monitor fails and/or recovers. (Default `false`).
     */
    muted?: pulumi.Input<boolean>;
    /**
     * The name of the monitor.
     */
    name?: pulumi.Input<string>;
    /**
     * The parameters of the HTTP request.
     */
    request?: pulumi.Input<inputs.DnsMonitorRequest>;
    /**
     * A strategy for retrying failed check/monitor runs.
     */
    retryStrategy?: pulumi.Input<inputs.DnsMonitorRetryStrategy>;
    /**
     * Determines whether the monitor should run on all selected locations in parallel or round-robin. (Default `false`).
     */
    runParallel?: pulumi.Input<boolean>;
    /**
     * A list of tags for organizing and filtering checks and monitors.
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Create and resolve an incident based on the alert configuration. Useful for status page automation.
     */
    triggerIncident?: pulumi.Input<inputs.DnsMonitorTriggerIncident>;
    /**
     * When true, the account level alert settings will be used, not the alert setting defined on this monitor. (Default `true`).
     */
    useGlobalAlertSettings?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a DnsMonitor resource.
 */
export interface DnsMonitorArgs {
    /**
     * Determines whether the monitor will run periodically or not after being deployed.
     */
    activated: pulumi.Input<boolean>;
    /**
     * An array of channel IDs and whether they're activated or not. If you don't set at least one alert subscription for your monitor, we won't be able to alert you.
     */
    alertChannelSubscriptions?: pulumi.Input<pulumi.Input<inputs.DnsMonitorAlertChannelSubscription>[]>;
    /**
     * Determines the alert escalation policy for the monitor.
     */
    alertSettings?: pulumi.Input<inputs.DnsMonitorAlertSettings>;
    /**
     * The response time in milliseconds where the monitor should be considered degraded. Possible values are between `0` and `5000`. (Default `500`).
     */
    degradedResponseTime?: pulumi.Input<number>;
    /**
     * How often the monitor should run in minutes. Possible values are `0`, `1`, `2`, `5`, `10`, `15`, `30`, `60`, `120`, `180`, `360`, `720`, and `1440`.
     */
    frequency: pulumi.Input<number>;
    /**
     * To create a high frequency monitor, set `frequency` to `0` and `frequencyOffset` to `10`, `20`, or `30`.
     */
    frequencyOffset?: pulumi.Input<number>;
    /**
     * The ID of the check group that this monitor is part of.
     */
    groupId?: pulumi.Input<number>;
    /**
     * The position of the monitor in the check group. It determines in what order checks and monitors are run when a group is triggered from the API or from CI/CD.
     */
    groupOrder?: pulumi.Input<number>;
    /**
     * An array of one or more data center locations where to run the this monitor.
     */
    locations?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The response time in milliseconds where the monitor should be considered failing. Possible values are between `0` and `5000`. (Default `1000`).
     */
    maxResponseTime?: pulumi.Input<number>;
    /**
     * Determines if any notifications will be sent out when the monitor fails and/or recovers. (Default `false`).
     */
    muted?: pulumi.Input<boolean>;
    /**
     * The name of the monitor.
     */
    name?: pulumi.Input<string>;
    /**
     * The parameters of the HTTP request.
     */
    request: pulumi.Input<inputs.DnsMonitorRequest>;
    /**
     * A strategy for retrying failed check/monitor runs.
     */
    retryStrategy?: pulumi.Input<inputs.DnsMonitorRetryStrategy>;
    /**
     * Determines whether the monitor should run on all selected locations in parallel or round-robin. (Default `false`).
     */
    runParallel?: pulumi.Input<boolean>;
    /**
     * A list of tags for organizing and filtering checks and monitors.
     */
    tags?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Create and resolve an incident based on the alert configuration. Useful for status page automation.
     */
    triggerIncident?: pulumi.Input<inputs.DnsMonitorTriggerIncident>;
    /**
     * When true, the account level alert settings will be used, not the alert setting defined on this monitor. (Default `true`).
     */
    useGlobalAlertSettings?: pulumi.Input<boolean>;
}
