// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class MaintenanceWindow extends pulumi.CustomResource {
    /**
     * Get an existing MaintenanceWindow resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: MaintenanceWindowState, opts?: pulumi.CustomResourceOptions): MaintenanceWindow {
        return new MaintenanceWindow(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'checkly:index/maintenanceWindow:MaintenanceWindow';

    /**
     * Returns true if the given object is an instance of MaintenanceWindow.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MaintenanceWindow {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MaintenanceWindow.__pulumiType;
    }

    public readonly endsAt!: pulumi.Output<string>;
    public readonly name!: pulumi.Output<string>;
    public readonly repeatEndsAt!: pulumi.Output<string | undefined>;
    public readonly repeatInterval!: pulumi.Output<number | undefined>;
    public readonly repeatUnit!: pulumi.Output<string | undefined>;
    public readonly startsAt!: pulumi.Output<string>;
    public readonly tags!: pulumi.Output<string[] | undefined>;

    /**
     * Create a MaintenanceWindow resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MaintenanceWindowArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: MaintenanceWindowArgs | MaintenanceWindowState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as MaintenanceWindowState | undefined;
            resourceInputs["endsAt"] = state ? state.endsAt : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["repeatEndsAt"] = state ? state.repeatEndsAt : undefined;
            resourceInputs["repeatInterval"] = state ? state.repeatInterval : undefined;
            resourceInputs["repeatUnit"] = state ? state.repeatUnit : undefined;
            resourceInputs["startsAt"] = state ? state.startsAt : undefined;
            resourceInputs["tags"] = state ? state.tags : undefined;
        } else {
            const args = argsOrState as MaintenanceWindowArgs | undefined;
            if ((!args || args.endsAt === undefined) && !opts.urn) {
                throw new Error("Missing required property 'endsAt'");
            }
            if ((!args || args.startsAt === undefined) && !opts.urn) {
                throw new Error("Missing required property 'startsAt'");
            }
            resourceInputs["endsAt"] = args ? args.endsAt : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["repeatEndsAt"] = args ? args.repeatEndsAt : undefined;
            resourceInputs["repeatInterval"] = args ? args.repeatInterval : undefined;
            resourceInputs["repeatUnit"] = args ? args.repeatUnit : undefined;
            resourceInputs["startsAt"] = args ? args.startsAt : undefined;
            resourceInputs["tags"] = args ? args.tags : undefined;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(MaintenanceWindow.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering MaintenanceWindow resources.
 */
export interface MaintenanceWindowState {
    endsAt?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    repeatEndsAt?: pulumi.Input<string>;
    repeatInterval?: pulumi.Input<number>;
    repeatUnit?: pulumi.Input<string>;
    startsAt?: pulumi.Input<string>;
    tags?: pulumi.Input<pulumi.Input<string>[]>;
}

/**
 * The set of arguments for constructing a MaintenanceWindow resource.
 */
export interface MaintenanceWindowArgs {
    endsAt: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    repeatEndsAt?: pulumi.Input<string>;
    repeatInterval?: pulumi.Input<number>;
    repeatUnit?: pulumi.Input<string>;
    startsAt: pulumi.Input<string>;
    tags?: pulumi.Input<pulumi.Input<string>[]>;
}
